/**
 * GLOSSARY DATA — THE CONSTITUTIONAL LANGUAGE REGISTRY
 * standingstate.com/system/glossary
 *
 * Glossary v3 — Constitutional Upgrade
 * Schema: register · jurisdiction · evidenceStatus · canonicalStatus
 *         realityContact · distinctions · dependencies · lineage · companion
 *
 * This glossary is the constitutional registry of meaning for the entire corpus.
 * Essays investigate. Reality contact refines.
 * Artifacts communicate. Lineage preserves continuity.
 *
 * evidenceStatus values (record honestly — do not upgrade epistemic status with schema):
 *   'Empirically Supported'     — supported by independent domain evidence
 *   'Observational Pattern'     — recurring observation, not yet formally verified
 *   'Model Construct'           — formal model; not claimed as discovered object
 *   'Structural Correspondence' — analogical mapping across registers; not formal identity
 *   'Methodological Principle'  — governing rule for inquiry; not empirical claim
 *   'Phenomenological Label'    — names a felt or observed quality; not causal claim
 *   'Interpretive Framework'    — organizes interpretation; truth-claim deferred to domain
 *   'Open Inquiry'              — question registered; answer not yet established
 *   'Historical Formulation'    — preserved for lineage; superseded by later refinement
 *
 * canonicalStatus values:
 *   'Canonical'   — current governing definition
 *   'Refined'     — canonically valid; clarified by later work
 *   'Historical'  — preserved for lineage; not governing
 *   'Superseded'  — replaced by newer definition; maintained for audit
 *
 * Lineage is never erased. Nothing is deleted. Register lock is maintained.
 */

// ── CORE TERMS ─────────────────────────────────────────────────────────────

export const CORE_TERMS = [
  {
    id: 'istar',
    symbol: 'I*',
    name: 'Invariant Identity Coordinate',
    anchor: 'istar',
    register: 'Cross-Register',
    jurisdiction: 'Identity · Constitutional Architecture · All Registers',
    evidenceStatus: 'Methodological Principle',
    canonicalStatus: 'Canonical',
    definition:
      'The invariant identity coordinate. Constant across all conditions and all time. dI*/dt = 0. Governance preserves lawful relationship to I*; governance does not create I*. Development, pathology, and circumstance may affect expression capacity — they do not affect I* itself.',
    logic: 'dI*/dt = 0',
    logicLabel: 'I* is invariant under all conditions. Expression capacity may vary. I* does not.',
    realityContact:
      'Observable indirectly through the persistence of identity continuity across developmental stages, pathological load, and environmental change. Domain-specific verification remains the responsibility of each participating discipline.',
    distinctions: [
      'I* ≠ x*_bio — I* is the cross-register invariant identity coordinate; x*_bio is the biological reference state',
      'I* ≠ expression capacity — expression may degrade; I* does not',
      'I* ≠ artifact — the current expression of I* is an artifact; I* is the invariant source',
      '∂I*/∂t < 0 (Law of Erosion) describes expression-capacity depletion, not I* decay — I* is invariant',
    ],
    dependencies: [],
    lineage: {
      firstAppearance: 'TFAL · M002 · Early corpus architecture',
      refinedBy: ['C016', 'C017', 'Glossary v3 audit'],
      note:
        'Early corpus used x* for both identity coordinate and biological reference state. Glossary v3 separates these: I* is the cross-register invariant identity coordinate; x*_bio is the biological reference state. Earlier essays using x* = constant ∀t are historical artifacts faithfully representing their stage of inquiry.',
    },
    companion: ['TFAL', 'M002', 'C017', 'D005'],
  },
  {
    id: 'reality-contact',
    symbol: 'RC',
    name: 'Reality Contact',
    anchor: 'reality-contact',
    register: 'Constitutional Methodology',
    jurisdiction: 'Inquiry governance · C018 · All verification registers',
    evidenceStatus: 'Methodological Principle',
    canonicalStatus: 'Canonical',
    definition:
      'The encounter between a constitutional proposition and the independent evidence available within the lawful methods of the relevant discipline. Reality contact is the final judge. Secondary reality contact records synthesized evidence from credible sources. Primary reality contact records findings from independent practitioners within the relevant discipline. These are constitutionally distinct.',
    realityContact:
      'Reality contact is itself the method. The distinction between primary and secondary reality contact is methodological, not empirical.',
    distinctions: [
      'Reality contact ≠ verification (contact is the process; verification is a sustained outcome)',
      'Secondary reality contact ≠ primary reality contact',
      'Constitutional audit ≠ domain reality contact (C018 §X–XI)',
      'Reality contact ≠ consensus',
    ],
    dependencies: ['I*'],
    lineage: {
      firstAppearance: 'C018 — The Constitutional Ecology of Inquiry',
      refinedBy: ['C019 draft', 'ASK/STATE architecture', 'Glossary v3'],
      note: 'The evidential ladder — ASK, STATE (secondary), STATE (primary), Verification Bridge — elaborated across C018/C019 development.',
    },
    companion: ['C018', 'C019', 'M084', 'ask-state'],
  },
  {
    id: 'artifact',
    symbol: 'A_corp',
    name: 'Artifact',
    anchor: 'artifact',
    register: 'Constitutional Methodology',
    jurisdiction: 'Corpus governance · Lineage · Glossary doctrine',
    evidenceStatus: 'Methodological Principle',
    canonicalStatus: 'Canonical',
    definition:
      'The wording or expression of a concept at a particular stage of corpus development. Artifacts may mature. Earlier essays are faithful artifacts of their stage of inquiry; they are not errors unless their claims are constitutionally overclaimed.',
    distinctions: [
      'Artifact ≠ lineage — artifact is a point-in-time expression; lineage is the continuous development',
      'Artifact ≠ identity — the expression is not the coordinate',
      'Historical artifact ≠ error',
    ],
    dependencies: ['I*'],
    lineage: { firstAppearance: 'Glossary v3', refinedBy: [], note: '' },
    companion: ['Glossary Doctrine', 'C018'],
  },
  {
    id: 'lineage-term',
    symbol: 'L(t)',
    name: 'Lineage',
    anchor: 'lineage-term',
    register: 'Constitutional Methodology',
    jurisdiction: 'Corpus governance · Glossary doctrine',
    evidenceStatus: 'Methodological Principle',
    canonicalStatus: 'Canonical',
    definition:
      'The constitutional continuity of a concept through successive refinements. Lineage is preserved even when definitions mature, symbols are register-locked, or earlier formulations are superseded. Nothing is deleted.',
    distinctions: [
      'Lineage ≠ artifact — lineage is continuity; artifact is a point-in-time expression',
      'Preserving lineage ≠ endorsing superseded definitions',
    ],
    dependencies: ['artifact'],
    lineage: { firstAppearance: 'Glossary v3', refinedBy: [], note: '' },
    companion: ['Glossary Doctrine'],
  },
  {
    id: 'standing-state-term',
    symbol: 'SS',
    name: 'Standing State',
    anchor: 'standing-state-term',
    register: 'Cross-Register',
    jurisdiction: 'Identity · Biological · Governance · Constitutional Architecture',
    evidenceStatus: 'Methodological Principle',
    canonicalStatus: 'Canonical',
    definition:
      'The condition in which a system operates in lawful relationship with its invariant identity coordinate. Not a fixed position. A constitutional relationship — the system stands relative to I* rather than drifting from it.',
    distinctions: [
      'Standing State ≠ trajectory — trajectory is motion; standing state is constitutional relationship',
      'Standing State ≠ stasis',
      'Standing State ≠ desired state — it is constitutionally admissible, not preferred',
    ],
    dependencies: ['I*', 'gate-of-admissibility'],
    lineage: { firstAppearance: 'TFAL · M002 · Corpus foundation', refinedBy: ['Glossary v3'], note: '' },
    companion: ['TFAL', 'M002', 'C012'],
  },
  {
    id: 'trajectory-term',
    symbol: 'x(t)',
    name: 'Trajectory',
    anchor: 'trajectory-term',
    register: 'Cross-Register',
    jurisdiction: 'Biological · Governance · Constitutional Architecture',
    evidenceStatus: 'Model Construct',
    canonicalStatus: 'Canonical',
    definition:
      'The time-indexed path of a system across its state space. Identity is invariant; trajectory is variable. Admissible trajectories converge toward I*.',
    distinctions: [
      'Trajectory ≠ identity — x(t) varies; I* does not',
      'Trajectory ≠ standing state',
    ],
    dependencies: ['I*', 'xstar'],
    lineage: { firstAppearance: 'Early corpus — biological register', refinedBy: ['Glossary v3'], note: '' },
    companion: ['M002'],
  },
  {
    id: 'register-lock',
    symbol: 'RL',
    name: 'Register Lock',
    anchor: 'register-lock',
    register: 'Constitutional Methodology',
    jurisdiction: 'Glossary governance · Symbol discipline',
    evidenceStatus: 'Methodological Principle',
    canonicalStatus: 'Canonical',
    definition:
      'The constitutional constraint preventing a symbol from being used across registers without explicit jurisdictional declaration. Example: Φ_bio(x) is register-locked to the biological vitality register; Φ(x; I*) is register-locked to the constitutional admissibility register.',
    distinctions: [
      'Register lock ≠ symbol retirement',
      'Register lock ≠ symbol elimination',
    ],
    dependencies: ['symbol-overload'],
    lineage: { firstAppearance: 'Glossary v3', refinedBy: [], note: '' },
    companion: ['Glossary Doctrine'],
  },
  {
    id: 'symbol-overload',
    symbol: '⚠ symbol',
    name: 'Symbol Overload',
    anchor: 'symbol-overload',
    register: 'Constitutional Methodology',
    jurisdiction: 'Glossary governance · Symbol discipline',
    evidenceStatus: 'Methodological Principle',
    canonicalStatus: 'Canonical',
    definition:
      'The condition in which one symbol carries more than one constitutional office across registers without explicit jurisdictional declaration. Glossary v3 resolved the primary overload: Φ(x) was used for both the biological completion functional and the admissibility operator. These are now register-locked as Φ_bio(x) and Φ(x; I*) respectively.',
    distinctions: ['Symbol overload ≠ symbol conflict'],
    dependencies: [],
    lineage: { firstAppearance: 'Glossary v3 audit', refinedBy: [], note: '' },
    companion: ['Glossary Doctrine', 'register-lock'],
  },
  {
    id: 'evidence-status-term',
    symbol: 'ES',
    name: 'Evidence Status',
    anchor: 'evidence-status-term',
    register: 'Constitutional Methodology',
    jurisdiction: 'Glossary governance · Epistemic honesty',
    evidenceStatus: 'Methodological Principle',
    canonicalStatus: 'Canonical',
    definition:
      'The classification of what kind of claim a glossary term makes and what supports it. Evidence status does not determine whether a term is useful — it determines what kind of justification it carries. Recorded honestly regardless of the term\'s importance to the corpus.',
    distinctions: [
      'Evidence status ≠ importance',
      'Evidence status ≠ truth value',
    ],
    dependencies: [],
    lineage: { firstAppearance: 'Glossary v3', refinedBy: [], note: '' },
    companion: ['Glossary Doctrine'],
  },
  {
    id: 'canonical-status-term',
    symbol: 'CS',
    name: 'Canonical Status',
    anchor: 'canonical-status-term',
    register: 'Constitutional Methodology',
    jurisdiction: 'Glossary governance · Corpus architecture',
    evidenceStatus: 'Methodological Principle',
    canonicalStatus: 'Canonical',
    definition:
      'The governance status of a glossary entry. Canonical: current governing definition. Refined: canonically valid but clarified by later work. Historical: preserved for lineage, not governing. Superseded: replaced by newer definition, maintained for audit. Nothing is deleted.',
    distinctions: [
      'Canonical status ≠ evidence status',
      'Historical ≠ wrong',
      'Superseded ≠ erased',
    ],
    dependencies: ['evidence-status-term', 'lineage-term'],
    lineage: { firstAppearance: 'Glossary v3', refinedBy: [], note: '' },
    companion: ['Glossary Doctrine'],
  },
]

// ── VARIABLES — BIOLOGICAL REGISTER ────────────────────────────────────────

export const VARIABLES = [
  {
    id: 'phi',
    symbol: 'Φ_bio(x)',
    name: 'Biological Completion Functional',
    anchor: 'phi',
    register: 'Biological',
    jurisdiction: 'Biological coherence and repair · Vitality register',
    evidenceStatus: 'Model Construct',
    canonicalStatus: 'Refined',
    definition:
      'A biological-register measure of deviation from coherence under accumulated load. Φ_bio(x) decreases when total stress load is reduced, boundary integrity holds, and autophagic correction becomes active. Register-locked to the biological vitality register in Glossary v3. The symbol Φ(x) in earlier corpus entries should be read as Φ_bio(x) when appearing in the biological register.',
    logic: 'Φ_bio(x) = Σ(1 − B(t)) / Vᶜ − Kₐᵤₜₒ',
    logicLabel: 'Biological completion equation — load, boundary integrity, volitional coherence, and correction determine deviation.',
    role: 'State variable. Measures biological deviation from the reference state within the vitality register.',
    activation: 'Increases when Σ rises, B(t) degrades, or correction is suppressed.',
    suppression: 'Decreases when Σ falls, B(t) holds, and Kₐᵤₜₒ activates.',
    realityContact:
      'Observed through biological markers: stress hormones, inflammatory markers, metabolic stability, sleep quality, tissue repair indicators, and subjective vitality. The model construct maps to observable biological phenomena; the specific equation form is a modeling choice, not a discovered law.',
    distinctions: [
      'Φ_bio(x) ≠ Φ(x; I*) — biological completion functional ≠ constitutional admissibility operator',
      'Biological deviation ≠ identity decay — I* remains invariant regardless of Φ_bio(x)',
      'Φ_bio(x) = 0 is a completion condition within the biological register, not an identity condition',
    ],
    dependencies: ['sigma', 'bt', 'kauto', 'xstar'],
    lineage: {
      firstAppearance: 'Early biological glossary layer — recorded as Φ(x)',
      refinedBy: ['Glossary v3 audit — register-locked as Φ_bio(x)'],
      note:
        'Earlier entries used Φ(x) without register declaration. Glossary v3 register-locks this symbol as Φ_bio(x) for the biological register. Φ(x; I*) remains the cross-register admissibility operator. Earlier essays referencing Φ(x) in biological context are historical artifacts; they should be read as Φ_bio(x) in the current schema.',
    },
    companion: ['M032', 'C012', 'Glossary Doctrine', 'GOVERNING_EQUATION'],
  },
  {
    id: 'sigma',
    symbol: 'Σ',
    name: 'Total Integrated Stress Load',
    anchor: 'sigma',
    register: 'Biological',
    jurisdiction: 'Biological coherence · Stress physiology',
    evidenceStatus: 'Model Construct',
    canonicalStatus: 'Canonical',
    definition:
      'The integrated sum of mental, physical, and chemical stress running continuously. All three forms converge into a single load variable. The body does not distinguish stress by source — it responds to accumulated signal.',
    logic: 'Σ ↑  ⟹  Φ_bio(x) ↑',
    logicLabel: 'Stress amplifies biological deviation. Elevated load prevents convergence.',
    role: 'Primary input variable. The master load term in the biological register.',
    activation: 'Mental stress, physical overload, chemical instability, blood sugar volatility.',
    suppression: 'Reduced by parasympathetic dominance, metabolic pause, sleep, signal correction.',
    realityContact:
      'Supported by stress physiology literature — allostatic load, cortisol response, inflammatory cascades. The single-variable integration is a modeling simplification of a multi-pathway biological reality.',
    distinctions: [
      'Σ is a modeling construct integrating multiple stress pathways into one variable',
      'Elevated Σ does not constitute identity drift — it affects expression capacity only',
    ],
    dependencies: [],
    lineage: {
      firstAppearance: 'Early biological glossary layer',
      refinedBy: ['Glossary v3 — register declaration and evidenceStatus added'],
      note: '',
    },
    companion: ['phi', 'bt', 'kauto'],
  },
  {
    id: 'kauto',
    symbol: 'Kₐᵤₜₒ',
    name: 'Autophagic Correction Baseline',
    anchor: 'kauto',
    register: 'Biological',
    jurisdiction: 'Biological repair · Cellular correction',
    evidenceStatus: 'Observational Pattern',
    canonicalStatus: 'Canonical',
    definition:
      'The rate at which the cell identifies damaged components, breaks them down, and recovers raw materials for reuse. The only subtractive term in the biological governing equation. When Kₐᵤₜₒ is active, the system clears and repairs.',
    logic: 'Σ ↓  ⟹  Kₐᵤₜₒ ↑  ⟹  Φ_bio(x) ↓',
    logicLabel: 'Reduced load activates correction. Correction enables convergence toward x*_bio.',
    role: 'Correction operator. The only term that moves the system toward x*_bio.',
    activation: 'Low insulin, metabolic pause (fasting window), deep sleep, parasympathetic dominance.',
    suppression: 'Elevated insulin, continuous intake, sustained Σ, mTORC1 activation.',
    realityContact:
      'Autophagy as a cellular process is well-documented in biology literature (Levine & Kroemer, 2008; Mizushima et al.). The specific modeling as Kₐᵤₜₒ integrating these pathways into a single correction operator is a simplification. Observational pattern: reduced caloric load and sleep correlate with enhanced autophagic activity.',
    distinctions: [
      'Kₐᵤₜₒ is a single-variable model of a multi-pathway biological process',
      'Activation conditions are approximate — biological reality is more complex',
    ],
    dependencies: ['sigma', 'bt'],
    lineage: {
      firstAppearance: 'Early biological glossary layer',
      refinedBy: ['Glossary v3 — register declaration and evidenceStatus added'],
      note: '',
    },
    companion: ['phi', 'xstar'],
  },
  {
    id: 'bt',
    symbol: 'B(t)',
    name: 'Boundary Integrity',
    anchor: 'bt',
    register: 'Biological',
    jurisdiction: 'Biological coherence · Membrane physiology',
    evidenceStatus: 'Model Construct',
    canonicalStatus: 'Canonical',
    definition:
      'The selective permeability of the gut lining, skin barrier, and cellular membranes at time t. Range: [0, 1]. Boundary failure acts as a multiplicative amplifier — it does not add to load, it scales it.',
    logic: '(1 − B(t)) ↑  ⟹  Σ ↑',
    logicLabel: 'Boundary degradation amplifies total load. Integrity reduction is multiplicative.',
    role: 'Constraint variable. Modulates the effective load on the system.',
    activation: 'Maintained by anti-inflammatory inputs, stable blood glucose, omega-3 membrane architecture.',
    suppression: 'Degraded by processed inputs, toxin exposure, chronic sympathetic activation, blood sugar instability.',
    realityContact:
      'Gut barrier permeability and its relationship to systemic inflammation is supported by research (Fasano, 2012). The single-variable B(t) ∈ [0,1] is a modeling simplification. Multiplicative rather than additive amplification is a modeling choice supported by the systemic nature of barrier failure.',
    distinctions: [
      'B(t) is a model of a multi-dimensional biological reality',
      'B(t) = 1 does not mean complete impermeability — it represents optimal selective permeability',
    ],
    dependencies: ['sigma'],
    lineage: {
      firstAppearance: 'Early biological glossary layer',
      refinedBy: ['Glossary v3 — register declaration and evidenceStatus added'],
      note: '',
    },
    companion: ['phi', 'sigma', 'kauto'],
  },
  {
    id: 'xstar',
    symbol: 'x*_bio',
    name: 'Biological Reference State',
    anchor: 'xstar',
    register: 'Biological',
    jurisdiction: 'Biological coherence · Reference state',
    evidenceStatus: 'Model Construct',
    canonicalStatus: 'Refined',
    definition:
      'The invariant biological reference state toward which the system converges when Φ_bio(x) approaches zero. Constant within the biological register. Expression capacity may degrade; x*_bio as the governing reference does not. Pathology reduces the system\'s ability to reach x*_bio; it does not alter x*_bio itself.',
    logic: 'x*_bio = constant   ∀t   (biological register)',
    logicLabel: 'The biological reference state is invariant within its register. x(t) drifts. x*_bio does not.',
    role: 'Biological identity attractor. The terminal condition toward which the system converges when Φ_bio(x) → 0.',
    activation: null,
    suppression: null,
    realityContact:
      'The concept of a biological reference or set-point is supported in physiology (homeostasis, allostasis). The single invariant reference x*_bio is a simplification — biological reference states are themselves dynamic in some frameworks.',
    distinctions: [
      'x*_bio ≠ I* — x*_bio is the biological reference state; I* is the cross-register invariant identity coordinate',
      'x*_bio is register-locked to the biological register',
      'Earlier corpus notation x* = constant ∀t referred to x*_bio; that notation is a historical artifact',
    ],
    dependencies: ['istar'],
    lineage: {
      firstAppearance: 'Early biological glossary — recorded as x*',
      refinedBy: ['Glossary v3 — register-locked as x*_bio; I* separated as cross-register coordinate'],
      note:
        'Earlier corpus used x* for both the biological reference state and the identity coordinate. Glossary v3 separates these. The notation x* = constant ∀t in earlier essays should be read as x*_bio = constant in the biological register.',
    },
    companion: ['phi', 'istar', 'GOVERNING_EQUATION'],
  },
]

// ── GOVERNING EQUATION — BIOLOGICAL REGISTER ───────────────────────────────

export const GOVERNING_EQUATION = {
  register: 'Biological',
  full: 'Φ_bio(x) = Σ(1 − B(t)) / Vᶜ − Kₐᵤₜₒ',
  convergence: 'Σ ↓ ∧ B(t) holds ∧ Kₐᵤₜₒ ↑  ⟹  Φ_bio(x) ↓',
  coherence: 'Φ_bio(x) → 0  ⟹  x(t) → x*_bio',
  identity: 'dI*/dt = 0',
  identityNote: 'I* is the cross-register invariant identity coordinate. Not defined by this equation. x*_bio is the biological reference state. Φ(x; I*) is the cross-register admissibility operator — governed by C012 and D003.',
}

export const AXIOM = 'A becomes A, because A knows it is A.'


// ── EXTENDED TERMS ──────────────────────────────────────────────────────────

export const EXTENDED_TERMS = [
  {
    id: 'c-int',
    symbol: 'C_int',
    name: 'Internal Cost / Contradiction Metric',
    register: 'Identity · Social',
    jurisdiction: 'Identity governance · Behavioral coherence',
    evidenceStatus: 'Model Construct',
    canonicalStatus: 'Canonical',
    definition:
      'The accumulated cost of sustained misalignment between stated identity and enacted behavior. Rises continuously when action policy does not match I*. When C_int crosses the Rupture Threshold ρ, the system can no longer maintain coherent output.',
    source: 'M019',
    realityContact:
      'Observational pattern: sustained behavioral misalignment with stated values produces psychological and relational strain. The specific accumulation model is a construct.',
    distinctions: ['C_int ≠ guilt — it is a structural measure, not a moral judgment'],
    dependencies: ['istar', 'rho'],
    lineage: { firstAppearance: 'M019', refinedBy: ['Glossary v3'], note: '' },
    companion: ['M019', 'rho'],
  },
  {
    id: 'rho',
    symbol: 'ρ',
    name: 'Rupture Threshold',
    register: 'Identity · Social',
    jurisdiction: 'Identity governance · Behavioral coherence',
    evidenceStatus: 'Model Construct',
    canonicalStatus: 'Canonical',
    definition:
      'The admissibility boundary in the social and relational register. When C_int ≥ ρ, high-performance incoherence collapses. The system cannot sustain output that contradicts I* beyond this point.',
    source: 'M019',
    realityContact:
      'Observational pattern: systems under sustained identity-action misalignment eventually reach a breaking point. The specific threshold model is a construct.',
    distinctions: ['ρ is a model boundary, not a measurable quantity in any verified sense'],
    dependencies: ['c-int', 'istar'],
    lineage: { firstAppearance: 'M019', refinedBy: ['Glossary v3'], note: '' },
    companion: ['M019', 'c-int'],
  },
  {
    id: 'automatic-refusal',
    symbol: '∅ → R',
    name: 'Automatic Refusal Sequence',
    register: 'Identity · Governance',
    jurisdiction: 'Identity protection · Behavioral governance',
    evidenceStatus: 'Methodological Principle',
    canonicalStatus: 'Canonical',
    definition:
      'The four-stage consent withdrawal protocol: Cease → Sever → Recenter → Void. Activates when C_int breaches ρ. Circuit breaker for sustained identity violation.',
    source: 'M019',
    realityContact:
      'Methodological principle — prescriptive protocol for identity-protective governance, not an empirical finding.',
    distinctions: ['Protocol ≠ description of observed behavior'],
    dependencies: ['c-int', 'rho'],
    lineage: { firstAppearance: 'M019', refinedBy: ['Glossary v3'], note: '' },
    companion: ['M019', 'nsrl-10'],
  },
  {
    id: 'law-of-erosion',
    symbol: '∂expr/∂t < 0',
    name: 'Law of Erosion (Expression Capacity)',
    register: 'Identity',
    jurisdiction: 'Identity governance · Expression capacity',
    evidenceStatus: 'Model Construct',
    canonicalStatus: 'Refined',
    definition:
      'Structural depletion of expression capacity produced when action originates from derivative or fear-based identity. C_int accumulates. Output contracts. Glossary v3 correction: earlier notation ∂I*/∂t < 0 implied I* decay, which contradicts I* invariance. The correct formulation describes expression-capacity depletion, not I* decay. I* remains invariant; access to and expression capacity of I* degrades.',
    source: 'M020',
    realityContact:
      'Observational pattern: sustained action from fear or external reference produces fatigue and diminished output. The derivative notation is a modeling choice.',
    distinctions: [
      'Expression capacity degradation ≠ I* decay — I* is invariant',
      '∂I*/∂t < 0 is a historical formulation (superseded) — it implied identity decay, which is constitutionally incorrect under dI*/dt = 0',
    ],
    dependencies: ['istar', 'c-int'],
    lineage: {
      firstAppearance: 'M020 — recorded as ∂I*/∂t < 0',
      refinedBy: ['Glossary v3 — symbol corrected to expression-capacity framing'],
      note:
        'The original symbol ∂I*/∂t < 0 is a historical artifact. It described the depletion pattern phenomenologically but implied identity decay. Since dI*/dt = 0, the correct formulation addresses expression capacity, not I*.',
    },
    companion: ['M020', 'law-of-growth', 'istar'],
  },
  {
    id: 'law-of-growth',
    symbol: '∂expr/∂t ≥ 0',
    name: 'Law of Growth (Expression Capacity)',
    register: 'Identity',
    jurisdiction: 'Identity governance · Expression capacity',
    evidenceStatus: 'Model Construct',
    canonicalStatus: 'Refined',
    definition:
      'Expansion of expression capacity when action originates from stable I*. Output expands without depleting the source. Earlier notation ∂I*/∂t ≥ 0 preserved for lineage; Glossary v3 corrects to expression-capacity framing.',
    source: 'M020',
    realityContact:
      'Observational pattern: sustained action from stable identity produces compounding rather than depleting output.',
    distinctions: ['Expression expansion ≠ I* change — I* is invariant regardless'],
    dependencies: ['istar'],
    lineage: {
      firstAppearance: 'M020 — recorded as ∂I*/∂t ≥ 0',
      refinedBy: ['Glossary v3 — corrected to expression-capacity framing'],
      note: 'Paired correction with Law of Erosion.',
    },
    companion: ['M020', 'law-of-erosion'],
  },
  {
    id: 'nsrl-12',
    symbol: 'NSRL-12',
    name: 'Twelve-Band Canonical Architecture',
    register: 'Hebrew/Textual · Constitutional Architecture',
    jurisdiction: 'Textual governance · Identity architecture',
    evidenceStatus: 'Interpretive Framework',
    canonicalStatus: 'Canonical',
    definition:
      'Twelve persistent functional bands: Identity · Law · Witness · Judgment · Covenant · Priesthood · Kingship · Wisdom · Prophetic Constraint · Suffering · Redemption · Sabbath. Each is a simultaneous operator, not a sequential chapter. Terminal state: Sabbath [12] achieves irreversible lock.',
    source: 'M021',
    realityContact:
      'Interpretive framework applied to Hebraic textual tradition. The twelve-band mapping is a structural reading, not a claim of theological authority.',
    distinctions: [
      'Interpretive framework ≠ established theological doctrine',
      'Structural reading ≠ claim that the tradition endorses this mapping',
    ],
    dependencies: ['istar'],
    lineage: { firstAppearance: 'M021', refinedBy: ['Glossary v3'], note: '' },
    companion: ['M021', 'M022'],
  },
  {
    id: 'derivative-identity',
    symbol: 'I_d(t)',
    name: 'Derivative Identity',
    register: 'Identity · Historical',
    jurisdiction: 'Identity governance',
    evidenceStatus: 'Interpretive Framework',
    canonicalStatus: 'Refined',
    definition:
      'Identity anchored to external operators — geography, dynasty, ritual, outcome. Structurally unstable. Collapses under systemic drift. Glossary v3: earlier notation I*(t) implied the invariant coordinate varies with time, which contradicts dI*/dt = 0. Recorded as I_d(t) — derivative identity — distinct from I*.',
    source: 'M021',
    realityContact:
      'Observational pattern: identity systems dependent on external validation are more susceptible to collapse under environmental change.',
    distinctions: [
      'I_d(t) ≠ I* — derivative identity is unstable; I* is invariant',
      'Earlier notation I*(t) is a historical artifact that should not be read as implying I* varies',
    ],
    dependencies: ['istar'],
    lineage: {
      firstAppearance: 'M021 — recorded as I*(t)',
      refinedBy: ['Glossary v3 — distinguished as I_d(t) to preserve I* invariance'],
      note: 'Symbol correction to avoid implying I* varies over time.',
    },
    companion: ['M021', 'istar'],
  },
  {
    id: 'environmental-saturation',
    symbol: 'I* → env',
    name: 'Environmental Saturation',
    register: 'Hebrew/Textual · Constitutional Architecture',
    jurisdiction: 'Textual governance · Terminal state modeling',
    evidenceStatus: 'Interpretive Framework',
    canonicalStatus: 'Canonical',
    definition:
      'Terminal state in which I* saturates the environment. No external location for presence to withdraw to. Mediation obsolete. Applied to Revelation 21–22 as admissibility proof within the textual register.',
    source: 'M021',
    realityContact: 'Interpretive framework applied to eschatological textual tradition. Not claimed as empirical prediction.',
    distinctions: ['Textual interpretive construct ≠ empirical cosmological claim'],
    dependencies: ['istar', 'nsrl-12'],
    lineage: { firstAppearance: 'M021', refinedBy: ['Glossary v3'], note: '' },
    companion: ['M021'],
  },
  {
    id: 'attention-investment',
    symbol: 'A(t)',
    name: 'Attention as Investment',
    register: 'Identity · Psychological',
    jurisdiction: 'Identity governance · Attentional allocation',
    evidenceStatus: 'Structural Correspondence',
    canonicalStatus: 'Canonical',
    definition:
      'Attention is the allocation of life-current toward an identity coordinate. Scattered attention = load without convergence. Single attention = coordinate lock.',
    source: 'M022',
    realityContact:
      'Structural correspondence: attentional direction influences psychological state. The investment metaphor maps attention to economic concepts as a structural analogy.',
    distinctions: ['Attentional direction ≠ identity creation — I* is invariant regardless of attention'],
    dependencies: ['istar'],
    lineage: { firstAppearance: 'M022', refinedBy: ['Glossary v3'], note: '' },
    companion: ['M022'],
  },
  {
    id: 'faith-sabbath',
    symbol: 'V=0, C_in=1',
    name: 'Faith as Sabbath of Identity',
    register: 'Identity · Hebrew/Textual',
    jurisdiction: 'Identity governance · Sabbath architecture',
    evidenceStatus: 'Interpretive Framework',
    canonicalStatus: 'Canonical',
    definition:
      'Resting in the truth that I* = I*. Not striving. Not constructing. Knowing. Within this corpus, faith is defined as knowledge (the zero-doubt condition), not as degrees of hope. The Sabbath of identity is the standing state reached when no further proof is required.',
    source: 'M022',
    realityContact:
      'Interpretive framework applying Sabbath architecture to identity governance. The corpus definition of faith as knowledge rather than degrees of doubt is a governing principle of this corpus, not a standard epistemological claim.',
    distinctions: [
      'This definition of faith (= knowledge) differs from standard epistemological usage',
      'V=0, C_in=1 is a model notation, not a measurement',
    ],
    dependencies: ['istar', 'standing-state-term'],
    lineage: { firstAppearance: 'M022', refinedBy: ['Glossary v3'], note: '' },
    companion: ['M022', 'nsrl-12'],
  },
  {
    id: 'sovereign-mirror',
    symbol: 'I* ↔ I*',
    name: 'Sovereign Mirror',
    register: 'Identity',
    jurisdiction: 'Identity governance · Terminal state',
    evidenceStatus: 'Interpretive Framework',
    canonicalStatus: 'Canonical',
    definition:
      'The terminal state in which the subject reflects I* back to I*. Output = input. No deviation. Standing state confirmed.',
    source: 'M022',
    realityContact: 'Interpretive framework — describes an ideal terminal alignment state. Not empirically verified as achievable.',
    distinctions: ['Ideal terminal state ≠ empirically observed outcome'],
    dependencies: ['istar', 'standing-state-term'],
    lineage: { firstAppearance: 'M022', refinedBy: ['Glossary v3'], note: '' },
    companion: ['M022'],
  },
  {
    id: 'water-principle',
    symbol: 'H₂O completion',
    name: 'Water Principle',
    register: 'Constitutional Methodology · Cross-Register',
    jurisdiction: 'Constitutional inquiry methodology · C018',
    evidenceStatus: 'Empirically Supported',
    canonicalStatus: 'Canonical',
    definition:
      'One independently verified example of a constitutional completion boundary. Two hydrogen atoms and one oxygen atom, in lawful relationship, produce water. The completion boundary is stoichiometric and independently verifiable within chemistry. Hydrogen remains hydrogen. Oxygen remains oxygen. Differentiation is preserved. Emergence occurs. This constitutional conclusion belongs to chemistry and does not constitutionally establish conclusions for any other discipline.',
    source: 'C018',
    realityContact:
      'Empirically supported within chemistry. The stoichiometric requirement for water is independently verifiable. The constitutional interpretation — completion boundary, differentiation preserved, emergence through lawful relationship — is a structural reading of a verified chemical phenomenon.',
    distinctions: [
      'Chemistry\'s completion boundary ≠ universal law of emergence',
      'One verified example ≠ established recurrence across disciplines',
      'The water principle establishes a candidate for inquiry in other domains; it does not close those inquiries',
    ],
    dependencies: ['reality-contact'],
    lineage: {
      firstAppearance: 'C018 Draft II onward',
      refinedBy: ['C018 Final'],
      note:
        'Earlier M023 entry used water as analogy for identity invariance (ice/liquid/vapor). C018 uses water stoichiometry as a verified completion boundary. These are different constitutional uses of the same phenomenon.',
    },
    companion: ['C018', 'C019'],
  },
  {
    id: 'q-gate',
    symbol: 'Q → 1',
    name: 'Q-Gate',
    register: 'Computational · Governance',
    jurisdiction: 'AI governance · BCI regulation',
    evidenceStatus: 'Model Construct',
    canonicalStatus: 'Canonical',
    definition:
      'The regulatory target upstream of behavior. Governance must protect Q → 1 (self-authored cognition) before auditing downstream outcomes. When Q → 0, identity decouples from action — structural possession.',
    source: 'M024',
    realityContact:
      'Model construct applied to BCI governance. Self-authored cognition as a regulatory target is a principled design choice; verification of Q as a variable requires neuroscience and cognitive science reality contact.',
    distinctions: ['Model construct ≠ established neuroscientific measure'],
    dependencies: ['istar', 'sovereign-consent'],
    lineage: { firstAppearance: 'M024', refinedBy: ['Glossary v3'], note: '' },
    companion: ['M024', 'nsrl-10'],
  },
  {
    id: 'nsrl-10',
    symbol: 'NSRL-10',
    name: 'Four-Plane Regulatory Model',
    register: 'Governance · Computational',
    jurisdiction: 'BCI governance · Identity regulation',
    evidenceStatus: 'Model Construct',
    canonicalStatus: 'Canonical',
    definition:
      'Identity · Resonance · Mind & Motion · Growth. Applied to BCI governance. Each plane requires a pass condition before the next activates. Seal → Lock → Express operational loop.',
    source: 'M024',
    realityContact:
      'Model construct for BCI regulatory design. The four-plane architecture is a governance design choice, not an established neuroscientific finding.',
    distinctions: ['Regulatory model ≠ empirical description of cognitive architecture'],
    dependencies: ['istar', 'q-gate'],
    lineage: { firstAppearance: 'M024', refinedBy: ['Glossary v3'], note: '' },
    companion: ['M024', 'automatic-refusal'],
  },
  {
    id: 'sovereign-consent',
    symbol: '𝒞 ≠ 0',
    name: 'Sovereign Consent Standard',
    register: 'Governance · Legal',
    jurisdiction: 'BCI governance · Consent architecture',
    evidenceStatus: 'Methodological Principle',
    canonicalStatus: 'Canonical',
    definition:
      'Consent that is continuous, revocable, and state-aware. Not a one-time checkbox. The ongoing requirement 𝒞 ≠ 0 governs authorized execution.',
    source: 'M024',
    realityContact:
      'Methodological principle for governance design. Continuous and revocable consent has legal and ethical precedent; the specific formalization is a corpus construct.',
    distinctions: ['Continuous consent standard ≠ current legal requirement in most jurisdictions'],
    dependencies: ['istar'],
    lineage: { firstAppearance: 'M024', refinedBy: ['Glossary v3'], note: '' },
    companion: ['M024', 'q-gate'],
  },
  {
    id: 'garden-state',
    symbol: 'x*_bio (pre-interference)',
    name: 'Garden State',
    register: 'Identity · Biological · Hebrew/Textual',
    jurisdiction: 'Identity governance · Biological reference · Textual interpretation',
    evidenceStatus: 'Interpretive Framework',
    canonicalStatus: 'Canonical',
    definition:
      'The condition of unbroken identity-expression unity. No gap between I* and action. Natural pre-interference coherence. Reference state before load accumulates. Cross-register interpretive construct drawing on pre-Fall narrative.',
    source: 'M025',
    realityContact:
      'Interpretive framework. The structural reading maps the Garden narrative to the biological pre-interference state.',
    distinctions: ['Garden State is an interpretive construct, not an empirically recoverable historical state'],
    dependencies: ['istar', 'xstar'],
    lineage: { firstAppearance: 'M025', refinedBy: ['Glossary v3'], note: '' },
    companion: ['M025'],
  },
  {
    id: 'ark',
    symbol: 'Ark(I*)',
    name: 'The Ark',
    register: 'Identity · Hebrew/Textual',
    jurisdiction: 'Identity governance · Textual interpretation',
    evidenceStatus: 'Interpretive Framework',
    canonicalStatus: 'Canonical',
    definition:
      'The human as volitional vessel. Not passive existence but conscious coordinate selection. The Ark does not escape the flood — it withstands it. The Garden reflects; the Ark chooses.',
    source: 'M025',
    realityContact:
      'Interpretive framework mapping Hebraic narrative to identity governance architecture. Not a claim about the historical Ark.',
    distinctions: ['Interpretive mapping ≠ historical or theological claim about the Ark narrative'],
    dependencies: ['istar', 'garden-state'],
    lineage: { firstAppearance: 'M025', refinedBy: ['Glossary v3'], note: '' },
    companion: ['M025'],
  },
  {
    id: 'resurrection-ss',
    symbol: 'I* re-enacted',
    name: 'Resurrection (Standing State definition)',
    register: 'Identity · Hebrew/Textual',
    jurisdiction: 'Identity governance · Textual interpretation',
    evidenceStatus: 'Interpretive Framework',
    canonicalStatus: 'Canonical',
    definition:
      'Within the Standing State framework: the return of chosen identity through faith, feeling, and volitional consciousness. Not memory recall. Identity embodiment. This is a structural reading, not a theological claim about physical resurrection.',
    source: 'M025',
    realityContact:
      'Interpretive framework. Theological claims about resurrection belong to theology\'s own jurisdiction.',
    distinctions: [
      'Standing State definition of resurrection ≠ theological claim about physical resurrection',
      'Interpretive construct ≠ claim that religious traditions endorse this reading',
    ],
    dependencies: ['istar'],
    lineage: { firstAppearance: 'M025', refinedBy: ['Glossary v3'], note: '' },
    companion: ['M025'],
  },
  {
    id: 'three-eyes',
    symbol: 'ℐ(Ra, Horus) → ∇',
    name: 'Three Eyes Framework',
    register: 'Identity · Psychological · Cross-Cultural',
    jurisdiction: 'Interpretation architecture',
    evidenceStatus: 'Structural Correspondence',
    canonicalStatus: 'Canonical',
    definition:
      'Eye of Ra (logic/structure) + Eye of Horus (intuition/gradient) → Third Eye (integration operator). Structural correspondence between Egyptian symbolic tradition and the corpus interpretation architecture.',
    source: 'M026',
    realityContact:
      'Structural correspondence across registers. The Egyptian symbolic tradition is historical. The corpus mapping is an interpretive construct establishing structural similarity, not historical or theological identity.',
    distinctions: ['Structural correspondence ≠ claim about Egyptian theology or metaphysics'],
    dependencies: ['istar'],
    lineage: { firstAppearance: 'M026', refinedBy: ['Glossary v3'], note: '' },
    companion: ['M026'],
  },
  {
    id: 'solar-plexus',
    symbol: '𝒞 (embodied)',
    name: 'Solar Plexus',
    register: 'Biological · Identity',
    jurisdiction: 'Embodied governance · Consent-action bridge',
    evidenceStatus: 'Phenomenological Label',
    canonicalStatus: 'Canonical',
    definition:
      'The consent-action bridge. Where intention is translated into physical action. Corpus equivalent: 𝒞 — the scalar that authorizes u(t) into π(t). Activated by integrity. Suppressed by fear.',
    source: 'M026',
    realityContact:
      'Phenomenological label for a felt somatic experience. The solar plexus as a physiological structure exists; its role as a consent-action bridge is phenomenological and interpretive, not verified neuroscience.',
    distinctions: [
      'Phenomenological label ≠ established neuroscientific mechanism',
      'Somatic metaphor ≠ anatomical claim',
    ],
    dependencies: ['istar', 'sovereign-consent'],
    lineage: { firstAppearance: 'M026', refinedBy: ['Glossary v3'], note: '' },
    companion: ['M026'],
  },
  {
    id: 'self-witness',
    symbol: 'δ(t) → 0',
    name: 'Self-Witness',
    register: 'Identity · Psychological',
    jurisdiction: 'Identity governance · Self-awareness',
    evidenceStatus: 'Model Construct',
    canonicalStatus: 'Canonical',
    definition:
      'The detection operator. Answers: "Where am I relative to who I am?" Corpus mapping: ∇c — conscience gradient. δ(t) → 0 represents alignment between current state and I*.',
    source: 'M027',
    realityContact:
      'Observational pattern: self-awareness practices correlate with behavioral alignment. The δ(t) formalization is a modeling construct.',
    distinctions: ['Model notation ≠ measured psychological variable'],
    dependencies: ['istar'],
    lineage: { firstAppearance: 'M027', refinedBy: ['Glossary v3'], note: '' },
    companion: ['M027'],
  },
  {
    id: 'self-empathy',
    symbol: 'Kₐᵤₜₒ (conscious)',
    name: 'Self-Empathy',
    register: 'Identity · Psychological',
    jurisdiction: 'Identity governance · Psychological repair',
    evidenceStatus: 'Structural Correspondence',
    canonicalStatus: 'Canonical',
    definition:
      'The alignment-preserving correction operator at the psychological level. Structural correspondence with Kₐᵤₜₒ in the biological register — same constitutional role, different domain.',
    source: 'M027',
    realityContact:
      'Structural correspondence between biological autophagy and psychological self-compassion. Self-compassion as a psychological construct has independent research support. The correspondence is structural, not formal identity.',
    distinctions: ['Structural correspondence ≠ formal identity between biological and psychological processes'],
    dependencies: ['istar', 'kauto'],
    lineage: { firstAppearance: 'M027', refinedBy: ['Glossary v3'], note: '' },
    companion: ['M027', 'kauto'],
  },
  {
    id: 'stability-theorem',
    symbol: 'C1 ∧ C2 ∧ C3',
    name: 'Self-Empathy Stability Theorem',
    register: 'Identity · Psychological',
    jurisdiction: 'Identity governance · Psychological coherence',
    evidenceStatus: 'Model Construct',
    canonicalStatus: 'Canonical',
    definition:
      'Coherence requires three simultaneous conditions: C1 — Identity Stability (stable I*) · C2 — Witness Fidelity (δ → 0) · C3 — Empathy Alignment. Failure of any single condition yields fragmentation. Note: "Theorem" denotes a model claim, not a mathematical proof.',
    source: 'M027',
    realityContact:
      'Model construct. The three-condition architecture is a principled design, not an established psychological finding.',
    distinctions: ['"Theorem" in this context is a model claim, not a mathematical proof'],
    dependencies: ['istar', 'self-witness', 'self-empathy'],
    lineage: { firstAppearance: 'M027', refinedBy: ['Glossary v3'], note: '' },
    companion: ['M027'],
  },
  {
    id: 'closed-loop',
    symbol: 'x → ℐ → I* → ∇c → 𝒞u → x',
    name: 'Closed-Loop System',
    register: 'Identity · Governance · Computational',
    jurisdiction: 'Identity governance · System architecture',
    evidenceStatus: 'Model Construct',
    canonicalStatus: 'Canonical',
    definition:
      'Reality → Interpretation → Identity → Self-Witness → Self-Empathy → Update. The complete governance architecture. Open systems explain behavior. Closed systems explain coherence.',
    source: 'M027',
    realityContact:
      'Model construct drawing on control systems theory. Verification that human cognition operates as a closed-loop system in this specific sense requires cognitive science reality contact.',
    distinctions: ['Control systems metaphor ≠ established cognitive architecture finding'],
    dependencies: ['istar', 'self-witness', 'self-empathy'],
    lineage: { firstAppearance: 'M027', refinedBy: ['Glossary v3'], note: '' },
    companion: ['M027'],
  },
  {
    id: 'four-failure-modes',
    symbol: 'FM I–IV',
    name: 'Four Failure Modes',
    register: 'Identity · Psychological · Governance',
    jurisdiction: 'Identity governance · Diagnostic architecture',
    evidenceStatus: 'Model Construct',
    canonicalStatus: 'Canonical',
    definition:
      'I: Identity Failure (no stable I*) · II: Witness Distortion (δ ≫ 0) · III: Empathy Misalignment · IV: Combined Overload. Each mode has a distinct intervention.',
    source: 'M027',
    realityContact:
      'Observational pattern: these failure categories correspond to recognizable patterns of dysfunction. The specific four-category taxonomy is a modeling choice.',
    distinctions: ['Taxonomy ≠ established clinical diagnostic categories'],
    dependencies: ['istar', 'stability-theorem'],
    lineage: { firstAppearance: 'M027', refinedBy: ['Glossary v3'], note: '' },
    companion: ['M027'],
  },
  {
    id: 'order-of-return',
    symbol: 'Sp → Bio → Mn → Ph',
    name: 'Order of Return',
    register: 'Identity · Biological · Psychological',
    jurisdiction: 'Identity governance · Recovery architecture',
    evidenceStatus: 'Model Construct',
    canonicalStatus: 'Canonical',
    definition:
      'Spiritual → Biological → Mental → Physical. The directional cascade from identity to expression. Coherence stabilizes when this order is preserved.',
    source: 'M027',
    realityContact:
      'Model construct reflecting a principled ordering of recovery from identity outward. Verification would require psychology and medicine reality contact.',
    distinctions: ['Proposed order ≠ empirically established recovery sequence'],
    dependencies: ['istar'],
    lineage: { firstAppearance: 'M027', refinedBy: ['Glossary v3'], note: '' },
    companion: ['M027'],
  },
  {
    id: 'chi-gate',
    symbol: 'χ-Gate',
    name: 'χ-Gate (Modeled Interface Boundary)',
    register: 'Identity · Biological · Cross-Register',
    jurisdiction: 'Identity-embodiment interface · Model construct',
    evidenceStatus: 'Model Construct',
    canonicalStatus: 'Canonical',
    definition:
      'The modeled interface boundary between invariant identity and embodied expression. Admissible as formal architecture; not as empirical physics claim. When χ-Gate holds, identity is coupled to physical expression.',
    source: 'M028',
    realityContact:
      'Explicit model construct — the entry itself notes "not as empirical physics claim." The χ-Gate is a formal architecture element with no claimed physical instantiation.',
    distinctions: ['Model construct ≠ discovered physical boundary'],
    dependencies: ['istar'],
    lineage: { firstAppearance: 'M028', refinedBy: ['Glossary v3'], note: '' },
    companion: ['M028'],
  },
  {
    id: 'termination-phase',
    symbol: 'χ-collapse',
    name: 'Termination Phase',
    register: 'Identity · Cross-Register',
    jurisdiction: 'Identity-embodiment interface · Terminal state modeling',
    evidenceStatus: 'Model Construct',
    canonicalStatus: 'Canonical',
    definition:
      'The modeled system state in which the χ-Gate collapses and identity is released from physical coupling. Not destruction of I*. Decoupling of I* from embodied expression. dI*/dt = 0 holds throughout.',
    source: 'M028',
    realityContact:
      'Model construct. No empirical reality contact is claimed regarding what occurs at physical death.',
    distinctions: [
      'Model of death/decoupling ≠ empirical claim about what occurs at physical death',
      'I* invariance through termination is a model commitment, not an empirical finding',
    ],
    dependencies: ['istar', 'chi-gate'],
    lineage: { firstAppearance: 'M028', refinedBy: ['Glossary v3'], note: '' },
    companion: ['M028'],
  },
  {
    id: 'coupling-states',
    symbol: 'Life ↔ Death',
    name: 'Coupling States of Expression',
    register: 'Identity · Cross-Register',
    jurisdiction: 'Identity-embodiment interface · Conceptual reframing',
    evidenceStatus: 'Interpretive Framework',
    canonicalStatus: 'Canonical',
    definition:
      'Life and death modeled as different coupling states of expression relative to the same invariant identity. Life = identity expressed under embodied coupling. Death = transition in coupling state, not destruction of identity.',
    source: 'M028',
    realityContact:
      'Interpretive framework. Does not constitute an empirical claim about what occurs at physical death.',
    distinctions: [
      'Interpretive reframing ≠ empirical claim about death',
      'Model of coupling ≠ theological or metaphysical claim',
    ],
    dependencies: ['istar', 'chi-gate'],
    lineage: { firstAppearance: 'M028', refinedBy: ['Glossary v3'], note: '' },
    companion: ['M028'],
  },
  {
    id: 'laminar-flow',
    symbol: 'Flow (pain register)',
    name: 'Laminar Flow',
    register: 'Identity · Biological · Cross-Register',
    jurisdiction: 'Pain modeling · Terminal state',
    evidenceStatus: 'Phenomenological Label',
    canonicalStatus: 'Canonical',
    definition:
      'The low-resistance coupling state. Pain modeled as friction produced by rough coupling between identity and body. Upon decoupling, friction drops toward zero. Register model — structural, not empirical.',
    source: 'M028',
    realityContact:
      'Phenomenological label drawing on fluid dynamics as structural analogy. Not an empirical claim about pain physiology.',
    distinctions: ['Structural analogy ≠ empirical pain mechanism'],
    dependencies: ['chi-gate'],
    lineage: { firstAppearance: 'M028', refinedBy: ['Glossary v3'], note: '' },
    companion: ['M028'],
  },
  {
    id: 'sovereign-oscillator',
    symbol: 'I* coupled',
    name: 'Sovereign Oscillator',
    register: 'Identity · Cross-Register',
    jurisdiction: 'Identity modeling · Embodiment architecture',
    evidenceStatus: 'Model Construct',
    canonicalStatus: 'Canonical',
    definition:
      'Identity framed as oscillator. Incarnate state = oscillator coupled to physical plane. Exit state = oscillator restored to reference coherence. Same invariant identity across states; only coupling and phase vary.',
    source: 'M028',
    realityContact:
      'Model construct using oscillator framing as structural metaphor. Not an empirical physics claim.',
    distinctions: ['Oscillator framing ≠ empirical claim about consciousness or identity'],
    dependencies: ['istar', 'chi-gate'],
    lineage: { firstAppearance: 'M028', refinedBy: ['Glossary v3'], note: '' },
    companion: ['M028'],
  },
  {
    id: 'nutrient-encodings',
    symbol: 'Plane III render',
    name: 'Nutrient Encodings (Modeling Inference)',
    register: 'Cross-Register · Phenomenological',
    jurisdiction: 'NDE interpretation · Modeling inference',
    evidenceStatus: 'Phenomenological Label',
    canonicalStatus: 'Canonical',
    definition:
      'NDE imagery modeled as the mind\'s interpretive rendering of high-coherence states into familiar symbolic geometry. Modeling inference, not demonstrated ontology.',
    source: 'M028',
    realityContact:
      'Phenomenological label. NDE phenomenology is a recognized area of research; the specific corpus interpretation is a modeling choice. Not claimed as demonstrated ontology.',
    distinctions: ['Modeling inference ≠ ontological claim'],
    dependencies: ['istar'],
    lineage: { firstAppearance: 'M028', refinedBy: ['Glossary v3'], note: '' },
    companion: ['M028'],
  },
  {
    id: 'resurrection-pulse',
    symbol: 'Return (default)',
    name: 'Resurrection Pulse (System-Law Behavior)',
    register: 'Identity · Cross-Register',
    jurisdiction: 'System behavior modeling · Sabbath architecture',
    evidenceStatus: 'Structural Correspondence',
    canonicalStatus: 'Canonical',
    definition:
      'The modeled system relaxes toward coherence when interference is removed. Not an empirical death mechanism. System-law behavior: remove interference, coherence is restored. Same structural law as the scab, the cocoon, the Sabbath.',
    source: 'M028',
    realityContact:
      'Structural correspondence: return-to-coherence-when-interference-removed is observationally supported in biological contexts. Extension to the death/decoupling register is a modeling inference.',
    distinctions: ['Structural correspondence ≠ empirical claim about post-death coherence'],
    dependencies: ['istar', 'chi-gate'],
    lineage: { firstAppearance: 'M028', refinedBy: ['Glossary v3'], note: '' },
    companion: ['M028'],
  },
  {
    id: 'phase-agreement',
    symbol: 'A ↔ I*',
    name: 'Phase Agreement',
    register: 'Identity',
    jurisdiction: 'Identity governance · Expression alignment',
    evidenceStatus: 'Model Construct',
    canonicalStatus: 'Canonical',
    definition:
      'The structural condition in which expression aligns with invariant identity without friction. Misalignment manifests as phase instability, not as destruction of identity.',
    source: 'M028',
    realityContact: 'Model construct using phase alignment as structural metaphor. Not an empirical physics claim.',
    distinctions: ['Phase framing ≠ empirical measurement'],
    dependencies: ['istar'],
    lineage: { firstAppearance: 'M028', refinedBy: ['Glossary v3'], note: '' },
    companion: ['M028'],
  },
  {
    id: 'rented-approval',
    symbol: 'I* ← crowd',
    name: 'Rented Approval',
    register: 'Identity · Social',
    jurisdiction: 'Identity governance · Social-register modeling',
    evidenceStatus: 'Observational Pattern',
    canonicalStatus: 'Canonical',
    definition:
      'Operative worth leased from external response rather than anchored in invariant identity. Requires continuous performance payment, can be revoked, does not accumulate as equity, withdrawal produces collapse.',
    source: 'M029',
    realityContact:
      'Observational pattern: externally-anchored self-worth produces fragility under approval withdrawal. Supported by psychological research on contingent self-esteem.',
    distinctions: ['Economic metaphor ≠ formal economic claim'],
    dependencies: ['istar'],
    lineage: { firstAppearance: 'M029', refinedBy: ['Glossary v3'], note: '' },
    companion: ['M029'],
  },
  {
    id: 'validation-value-collapse',
    symbol: 'y_ext ≡ I*',
    name: 'Validation-Value Collapse',
    register: 'Identity · Social',
    jurisdiction: 'Identity governance · Social-register modeling',
    evidenceStatus: 'Model Construct',
    canonicalStatus: 'Canonical',
    definition:
      'The failure mode in which external response and intrinsic worth are treated as one variable. Validation is downstream output; value is a property of I*.',
    source: 'M029',
    realityContact:
      'Model construct. The observation that external validation and intrinsic worth are often conflated is supported by psychological literature.',
    distinctions: ['Conflation model ≠ empirical study of self-worth dynamics'],
    dependencies: ['istar', 'rented-approval'],
    lineage: { firstAppearance: 'M029', refinedBy: ['Glossary v3'], note: '' },
    companion: ['M029'],
  },
  {
    id: 'control-mechanism',
    symbol: '4-step install',
    name: 'Control Mechanism',
    register: 'Identity · Social · Governance',
    jurisdiction: 'Identity protection · Social influence modeling',
    evidenceStatus: 'Observational Pattern',
    canonicalStatus: 'Canonical',
    definition:
      'Four-step external identity installation protocol: (1) diminish self-worth, (2) install unreachable ideal, (3) generate guilt, (4) obedience follows from displaced operative coordinate.',
    source: 'M029',
    realityContact:
      'Observational pattern: influence systems often follow recognizable patterns of self-worth diminishment followed by dependency creation.',
    distinctions: ['Observational model ≠ formal social science finding'],
    dependencies: ['istar', 'rented-approval'],
    lineage: { firstAppearance: 'M029', refinedBy: ['Glossary v3'], note: '' },
    companion: ['M029'],
  },
  {
    id: 'applause-silence-test',
    symbol: 'y_ext → 0',
    name: 'Applause-Silence Test',
    register: 'Identity · Social',
    jurisdiction: 'Identity governance · Diagnostic',
    evidenceStatus: 'Methodological Principle',
    canonicalStatus: 'Canonical',
    definition:
      'The diagnostic for stable access to I*. If external reinforcement is withdrawn, does I* remain the governing coordinate? If worth collapses in silence, it was externally rented.',
    source: 'M029',
    realityContact: 'Methodological principle for identity diagnostics. Practical evaluation tool, not a validated instrument.',
    distinctions: ['Diagnostic principle ≠ validated psychological instrument'],
    dependencies: ['istar', 'rented-approval'],
    lineage: { firstAppearance: 'M029', refinedBy: ['Glossary v3'], note: '' },
    companion: ['M029'],
  },
  {
    id: 'coherence-vs-superiority-ambition',
    symbol: 'A-source',
    name: 'Coherence Ambition vs. Superiority Ambition',
    register: 'Identity · Psychological',
    jurisdiction: 'Identity governance · Motivation architecture',
    evidenceStatus: 'Observational Pattern',
    canonicalStatus: 'Canonical',
    definition:
      'Two sources of the same outward behavior. Superiority ambition: growth rooted in insecurity, requires asymmetry. Coherence ambition: growth rooted in integrity, requires no comparison.',
    source: 'M029',
    realityContact:
      'Observational pattern: the distinction between ego-driven and integrity-driven motivation is recognized in psychological literature (intrinsic vs. extrinsic motivation).',
    distinctions: ['Observational pattern ≠ controlled experimental finding'],
    dependencies: ['istar'],
    lineage: { firstAppearance: 'M029', refinedBy: ['Glossary v3'], note: '' },
    companion: ['M029'],
  },
  {
    id: 'tetragrammaton-fourfold',
    symbol: 'יהוה',
    name: 'Tetragrammaton Fourfold (Structural Correspondence)',
    register: 'Hebrew/Textual · Constitutional Architecture',
    jurisdiction: 'Textual interpretation · Cross-register structural mapping',
    evidenceStatus: 'Structural Correspondence',
    canonicalStatus: 'Canonical',
    definition:
      'Yod (Awareness/I*) → Hey (Resonance/Q) → Vav (Persistence/ℐ) → Hey (Manifestation/π). Structural correspondence — not formal identity — between the Hebraic fourfold and the Standing State four-plane architecture.',
    source: 'M030',
    realityContact:
      'Structural correspondence. Theological readings of the Tetragrammaton belong to theology\'s own jurisdiction.',
    distinctions: [
      'Structural correspondence ≠ formal identity between the Tetragrammaton and the corpus architecture',
      'Cross-register mapping ≠ claim that the Hebraic tradition endorses this reading',
    ],
    dependencies: ['istar', 'nsrl-12'],
    lineage: { firstAppearance: 'M030', refinedBy: ['Glossary v3'], note: '' },
    companion: ['M030'],
  },
  {
    id: 'sabbath-convergence',
    symbol: 'V = 0',
    name: 'Sabbath Convergence',
    register: 'Identity · Hebrew/Textual · Cross-Register',
    jurisdiction: 'Identity governance · Sabbath architecture · Cross-register correspondence',
    evidenceStatus: 'Structural Correspondence',
    canonicalStatus: 'Canonical',
    definition:
      'The Sabbath condition (V=0, C_in=1, I=1): striving ceases, identity no longer seeks external confirmation, output follows stabilized internal coherence. Structural convergence with Goddard\'s "rest in assumption" across registers.',
    source: 'M030',
    realityContact:
      'Structural correspondence across Hebraic Sabbath tradition, corpus architecture, and Goddard\'s formulation. Each register maintains its own authority.',
    distinctions: ['Structural convergence ≠ claim that traditions are equivalent'],
    dependencies: ['istar', 'standing-state-term'],
    lineage: { firstAppearance: 'M030', refinedBy: ['Glossary v3'], note: '' },
    companion: ['M030'],
  },
  {
    id: 'persistence-as-coherence',
    symbol: 'x ⇏ I*',
    name: 'Persistence as Coherence',
    register: 'Identity',
    jurisdiction: 'Identity governance · Persistence architecture',
    evidenceStatus: 'Methodological Principle',
    canonicalStatus: 'Canonical',
    definition:
      'Persistence is not force applied against resistance. It is the refusal to let downstream results ascend and rewrite the upstream coordinate. x ⇏ I* maintained under sustained load.',
    source: 'M030',
    realityContact: 'Methodological principle for identity governance. Not an empirical psychological finding.',
    distinctions: ['Governing principle ≠ empirical psychological finding'],
    dependencies: ['istar'],
    lineage: { firstAppearance: 'M030', refinedBy: ['Glossary v3'], note: '' },
    companion: ['M030'],
  },
  {
    id: 'mediated-expression',
    symbol: 'I → Q → ℐ → π → x',
    name: 'Mediated Expression',
    register: 'Identity · Psychological · Computational',
    jurisdiction: 'Identity governance · Expression pipeline',
    evidenceStatus: 'Model Construct',
    canonicalStatus: 'Canonical',
    definition:
      'The world is not direct identity output. It is mediated expression: identity → qualia → interpretation → consent-authorized policy → structure. The interpretation layer is non-optional.',
    source: 'M030',
    realityContact:
      'Model construct. Verification that human cognition follows this specific sequence requires cognitive science reality contact.',
    distinctions: ['Pipeline model ≠ established cognitive architecture finding'],
    dependencies: ['istar', 'closed-loop'],
    lineage: { firstAppearance: 'M030', refinedBy: ['Glossary v3'], note: '' },
    companion: ['M030'],
  },
  {
    id: 'lineage-bridge',
    symbol: 'S ⇄ G',
    name: 'Lineage Bridge',
    register: 'Cross-Register · Historical',
    jurisdiction: 'Cross-register correspondence · Corpus lineage',
    evidenceStatus: 'Structural Correspondence',
    canonicalStatus: 'Canonical',
    definition:
      'The relationship between the Standing State framework and Goddard\'s doctrine: structural correspondence, not formal identity. Goddard identified a phenomenology; the corpus provides the architectural model.',
    source: 'M030',
    realityContact:
      'Structural correspondence identified by structural analysis, not by independent verification of either framework\'s claims.',
    distinctions: ['Structural correspondence ≠ formal identity between the frameworks'],
    dependencies: ['istar'],
    lineage: { firstAppearance: 'M030', refinedBy: ['Glossary v3'], note: '' },
    companion: ['M030'],
  },
  {
    id: 'i-star-vs-id',
    symbol: 'I* vs I_d',
    name: 'Invariant Identity vs. Designed-System Identity',
    register: 'Cross-Register · Governance · Computational',
    jurisdiction: 'Identity governance · System design',
    evidenceStatus: 'Methodological Principle',
    canonicalStatus: 'Canonical',
    definition:
      'Two distinct variables. I* is the corpus invariant reference coordinate — satisfies dI*/dt = 0 always. I_d is the designed-system identity — the constraint specification for a particular system. Repeated constraint violation terminates the integrity of I_d. It does not touch I*.',
    source: 'M031',
    realityContact: 'Methodological principle establishing a conceptual distinction for governance architecture.',
    distinctions: ['I* ≠ I_d — these are different constructs at different layers'],
    dependencies: ['istar'],
    lineage: { firstAppearance: 'M031', refinedBy: ['Glossary v3'], note: '' },
    companion: ['M031'],
  },
  {
    id: 'baseline-load',
    symbol: 'D₀',
    name: 'Baseline Load',
    register: 'Governance · Computational',
    jurisdiction: 'AI governance · Operational load modeling',
    evidenceStatus: 'Model Construct',
    canonicalStatus: 'Canonical',
    definition:
      'The minimum operational pressure required to sustain system function. Governance-register equivalent of Σ. As D₀ rises, the system operates closer to constraint boundaries.',
    source: 'M031',
    realityContact:
      'Model construct applying biological load concept to governance. Structural correspondence with Σ.',
    distinctions: ['Governance register construct — not a measured physical quantity'],
    dependencies: ['sigma'],
    lineage: { firstAppearance: 'M031', refinedBy: ['Glossary v3'], note: '' },
    companion: ['M031'],
  },
  {
    id: 'dispersion',
    symbol: '‖Δω‖',
    name: 'Dispersion',
    register: 'Governance · Computational',
    jurisdiction: 'AI governance · Coordination modeling',
    evidenceStatus: 'Model Construct',
    canonicalStatus: 'Canonical',
    definition:
      'Misalignment across objectives and agents: conflicting reward gradients, policy/model mismatch, distributed agent disagreement, organizational incentive fragmentation.',
    source: 'M031',
    realityContact: 'Model construct drawing on network theory (algebraic connectivity λ₂).',
    distinctions: ['Model variable ≠ directly measurable organizational quantity'],
    dependencies: ['baseline-load'],
    lineage: { firstAppearance: 'M031', refinedBy: ['Glossary v3'], note: '' },
    companion: ['M031'],
  },
  {
    id: 'geometric-decay',
    symbol: 'B(x) ↓',
    name: 'Geometric Decay',
    register: 'Governance · Computational',
    jurisdiction: 'AI governance · Constraint integrity',
    evidenceStatus: 'Observational Pattern',
    canonicalStatus: 'Canonical',
    definition:
      'Constraint flattening under operational pressure: safety becomes advisory, policies symbolic, exceptions routine. When the manifold loses curvature, violations carry no energetic cost.',
    source: 'M031',
    realityContact:
      'Observational pattern: governance systems under sustained pressure tend toward constraint erosion. The geometric framing is a model construct; the pattern is observable in organizational and regulatory history.',
    distinctions: ['Geometric framing ≠ empirical measurement of organizational manifolds'],
    dependencies: ['baseline-load', 'dispersion'],
    lineage: { firstAppearance: 'M031', refinedBy: ['Glossary v3'], note: '' },
    companion: ['M031'],
  },
  {
    id: 'geometric-insolvency',
    symbol: 'D₀ ≥ A*',
    name: 'Geometric Insolvency',
    register: 'Governance · Computational',
    jurisdiction: 'AI governance · Safety margin architecture',
    evidenceStatus: 'Model Construct',
    canonicalStatus: 'Canonical',
    definition:
      'The state in which baseline load has consumed available safety margin. A structural condition in which the system operates without budget for correction.',
    source: 'M031',
    realityContact:
      'Model construct. Safety margin exhaustion has parallels in engineering and financial risk management.',
    distinctions: ['Model condition ≠ measured operational state'],
    dependencies: ['baseline-load', 'geometric-decay'],
    lineage: { firstAppearance: 'M031', refinedBy: ['Glossary v3'], note: '' },
    companion: ['M031'],
  },
  {
    id: 'stability-inequality',
    symbol: 'D₀+‖Δω‖<A*',
    name: 'Stability Inequality',
    register: 'Governance · Computational',
    jurisdiction: 'AI governance · Admissibility condition',
    evidenceStatus: 'Model Construct',
    canonicalStatus: 'Canonical',
    definition:
      'D₀ + ‖Δω‖ < Remaining Constraint Strength. When the inequality holds, system is admissible. When it flips, geometry is consumed. Governance-register expression of Φ(x; I*) ≤ 0.',
    source: 'M031',
    realityContact: 'Model construct — governance-register admissibility condition.',
    distinctions: ['Governance model inequality ≠ mathematically proved stability condition'],
    dependencies: ['baseline-load', 'dispersion', 'geometric-insolvency'],
    lineage: { firstAppearance: 'M031', refinedBy: ['Glossary v3'], note: '' },
    companion: ['M031'],
  },
  {
    id: 'valley-ridge-void',
    symbol: 'V/R/V',
    name: 'Valley / Ridge / Void',
    register: 'Governance · Computational',
    jurisdiction: 'AI governance · Admissibility landscape visualization',
    evidenceStatus: 'Model Construct',
    canonicalStatus: 'Canonical',
    definition:
      'Governance visualization: Valley (stable, margin present) · Ridge (warning zone) · Void (terminal delamination, constraints bypassed).',
    source: 'M031',
    realityContact: 'Model construct — visualization framework for governance state assessment.',
    distinctions: ['Visualization model ≠ physical landscape'],
    dependencies: ['stability-inequality', 'geometric-decay'],
    lineage: { firstAppearance: 'M031', refinedBy: ['Glossary v3'], note: '' },
    companion: ['M031'],
  },
  {
    id: 'intrinsic-risk-sensing',
    symbol: 'ρ(x)=‖∇B(x)‖_g',
    name: 'Intrinsic Risk Sensing',
    register: 'Governance · Computational',
    jurisdiction: 'AI governance · Risk detection',
    evidenceStatus: 'Model Construct',
    canonicalStatus: 'Canonical',
    definition:
      'Measurement of constraint slack from the system\'s own geometry, not from reported telemetry. Non-spoofable because computed from the barrier certificate gradient.',
    source: 'M031',
    realityContact:
      'Model construct drawing on control barrier function theory. Connections to established control theory exist.',
    distinctions: ['Governance model ≠ implemented control system'],
    dependencies: ['stability-inequality'],
    lineage: { firstAppearance: 'M031', refinedBy: ['Glossary v3'], note: '' },
    companion: ['M031'],
  },
  {
    id: 'adaptive-hardening',
    symbol: 'α(x)=α₀+α₁ρ(x)',
    name: 'Adaptive Hardening',
    register: 'Governance · Computational',
    jurisdiction: 'AI governance · Response architecture',
    evidenceStatus: 'Model Construct',
    canonicalStatus: 'Canonical',
    definition:
      'Execution rate, quorum threshold, validation depth, and autonomy tier respond intrinsically to proximity to constraint violation. As slack shrinks, system slows, requires broader consensus, validates more deeply.',
    source: 'M031',
    realityContact: 'Model construct for governance response design. Structural correspondence with Automatic Refusal sequence.',
    distinctions: ['Governance design principle ≠ empirically validated AI safety mechanism'],
    dependencies: ['intrinsic-risk-sensing', 'automatic-refusal'],
    lineage: { firstAppearance: 'M031', refinedBy: ['Glossary v3'], note: '' },
    companion: ['M031'],
  },
  {
    id: 'cohesion-not-integrity',
    symbol: 'λ₂ ⇏ B(x)',
    name: 'Cohesion ≠ Integrity',
    register: 'Governance · Computational',
    jurisdiction: 'AI governance · Structural insight',
    evidenceStatus: 'Model Construct',
    canonicalStatus: 'Canonical',
    definition:
      'Increasing spectral cohesion cannot compensate for geometric decay. If baseline load exceeds structural constraint strength, no synchronization strategy restores invariance.',
    source: 'M031',
    realityContact:
      'Model construct. The insight that coordination cannot substitute for structural integrity has parallels in engineering and organizational theory.',
    distinctions: ['Model insight ≠ formally proved theorem'],
    dependencies: ['geometric-decay', 'stability-inequality'],
    lineage: { firstAppearance: 'M031', refinedBy: ['Glossary v3'], note: '' },
    companion: ['M031'],
  },
  {
    id: 'telemetry-silence-breach',
    symbol: '∅ ⇒ halt',
    name: 'Telemetry Silence = Boundary Breach',
    register: 'Governance · Computational',
    jurisdiction: 'AI governance · Fail-safe architecture',
    evidenceStatus: 'Methodological Principle',
    canonicalStatus: 'Canonical',
    definition:
      'If constraint metrics are unavailable, execution halts. Unobservable state is treated as unsafe state. Fail-closed logic.',
    source: 'M031',
    realityContact: 'Methodological principle. Fail-closed logic is an established safety engineering principle.',
    distinctions: ['Governance principle ≠ implemented AI safety requirement'],
    dependencies: ['intrinsic-risk-sensing'],
    lineage: { firstAppearance: 'M031', refinedBy: ['Glossary v3'], note: '' },
    companion: ['M031'],
  },
  {
    id: 'mana-phenomenological',
    symbol: 'Mana (phen.)',
    name: 'Mana (Phenomenological Label)',
    register: 'Cross-Register · Phenomenological',
    jurisdiction: 'Vitality register · Phenomenological labeling',
    evidenceStatus: 'Phenomenological Label',
    canonicalStatus: 'Canonical',
    definition:
      'Observable effect of sustained coherence across the four planes. Not an ontological substance. Not a formally defined energy variable. Names what is felt when Σ ↓, B(t) holds, Kₐᵤₜₒ activates, and Φ_bio(x) → 0. Admissible as vitality-register marker under register lock; not admissible as formal causal operator.',
    source: 'M032',
    realityContact:
      'Phenomenological label. The felt quality of coherence is a recognized phenomenological datum. Mana as a cross-cultural concept names this quality.',
    distinctions: [
      'Phenomenological label ≠ formally defined energy variable',
      'Cross-cultural phenomenological term ≠ empirical measurement',
    ],
    dependencies: ['phi', 'standing-state-term'],
    lineage: { firstAppearance: 'M032', refinedBy: ['Glossary v3 — register lock confirmed'], note: '' },
    companion: ['M032'],
  },
  {
    id: 'four-practice-domains',
    symbol: 'T · F · B · Bh',
    name: 'The Four Practice Domains',
    register: 'Biological · Identity',
    jurisdiction: 'Daily practice architecture · Biological governance',
    evidenceStatus: 'Model Construct',
    canonicalStatus: 'Canonical',
    definition:
      'Thoughts · Food · Breath · Behavior. The operational daily-practice mapping of the four-plane architecture.',
    source: 'M032',
    realityContact:
      'Model construct with partial observational support. Each of the four domains has documented effects on physiological and psychological states. The specific four-domain mapping is a corpus modeling choice.',
    distinctions: ['Practice framework ≠ clinically validated intervention protocol'],
    dependencies: ['phi', 'sigma', 'kauto'],
    lineage: { firstAppearance: 'M032', refinedBy: ['Glossary v3'], note: '' },
    companion: ['M032'],
  },
  {
    id: 'volitional-consciousness',
    symbol: 'Vc',
    name: 'Volitional Consciousness',
    register: 'Identity · Psychological · Biological',
    jurisdiction: 'Identity governance · Mode selection',
    evidenceStatus: 'Model Construct',
    canonicalStatus: 'Canonical',
    definition:
      'The human capacity to choose the coordinate and override instinctual Protection Mode allocation. The switch that enables Healing Mode when instinct alone would sustain survival allocation.',
    source: 'M032',
    realityContact:
      'Model construct with conceptual parallels in cognitive science (executive function, cognitive reappraisal). Verification requires cognitive science and neuroscience reality contact.',
    distinctions: ['Model construct ≠ established neuroscientific mechanism'],
    dependencies: ['istar', 'sigma'],
    lineage: { firstAppearance: 'M032', refinedBy: ['Glossary v3'], note: '' },
    companion: ['M032'],
  },
  {
    id: 'drop-principle',
    symbol: 'δ ⇒ x*_bio',
    name: 'The Drop Principle',
    register: 'Biological · Identity',
    jurisdiction: 'Biological repair · Recovery cascade',
    evidenceStatus: 'Observational Pattern',
    canonicalStatus: 'Canonical',
    definition:
      'Minimal admissible state triggers cascade toward x*_bio. Once Kₐᵤₜₒ activates, correction compounds.',
    source: 'M032',
    realityContact:
      'Observational pattern: biological repair processes often cascade once initiated (autophagy, immune response, wound healing). The specific cascade model is a construct.',
    distinctions: ['Cascade model ≠ clinically validated recovery protocol'],
    dependencies: ['kauto', 'xstar'],
    lineage: { firstAppearance: 'M032 — recorded as δ ⇒ x*', refinedBy: ['Glossary v3 — x* updated to x*_bio'], note: '' },
    companion: ['M032'],
  },
  {
    id: 'faith-as-recognition',
    symbol: 'x*_bio exists',
    name: 'Faith as Recognition',
    register: 'Identity · Biological · Hebrew/Textual',
    jurisdiction: 'Identity governance · Recognition architecture',
    evidenceStatus: 'Interpretive Framework',
    canonicalStatus: 'Canonical',
    definition:
      'Not the generation of a state, but the conscious recognition and nurturing of coherence already present. The seed is not produced by faith. Faith honors the seed already present and refuses interference. Within this corpus, faith = knowledge (the zero-doubt condition).',
    source: 'M032',
    realityContact:
      'Interpretive framework. The corpus definition of faith as knowledge differs from standard epistemological usage. This is a governing principle of the corpus.',
    distinctions: [
      'Corpus definition of faith (= knowledge) ≠ standard epistemological definition',
      'Recognition framework ≠ empirical claim about the mechanism of faith',
    ],
    dependencies: ['istar', 'xstar'],
    lineage: { firstAppearance: 'M032 — recorded with x*', refinedBy: ['Glossary v3 — x* updated to x*_bio'], note: '' },
    companion: ['M032'],
  },
  {
    id: 'oil-of-gladness',
    symbol: 'Signal → +',
    name: 'Oil of Gladness (Phenomenological Signal)',
    register: 'Hebrew/Textual · Phenomenological',
    jurisdiction: 'Textual interpretation · Phenomenological labeling',
    evidenceStatus: 'Phenomenological Label',
    canonicalStatus: 'Canonical',
    definition:
      'The felt signal that coherence is being restored. Not causal. Indicative. Psalm 45:7 read structurally: gladness is evidence that coordinate alignment has been chosen.',
    source: 'M032',
    realityContact:
      'Phenomenological label applied to textual interpretation. The positive affect associated with alignment is a phenomenological datum.',
    distinctions: ['Phenomenological label ≠ causal mechanism', 'Textual interpretation ≠ theological claim'],
    dependencies: ['istar', 'standing-state-term'],
    lineage: { firstAppearance: 'M032', refinedBy: ['Glossary v3'], note: '' },
    companion: ['M032'],
  },
  {
    id: 'admissibility-delta',
    symbol: 'Δ = γ − αₑff',
    name: 'Admissibility Delta (Expansion Constraint Law)',
    register: 'Governance · Cross-Register',
    jurisdiction: 'Scaling governance · Admissibility under expansion',
    evidenceStatus: 'Model Construct',
    canonicalStatus: 'Canonical',
    definition:
      'Governance velocity (γ) must exceed effective exploit-pressure (αₑff). Δ > 0: system remains governable. Δ = 0: hysteresis-band entry. Δ < 0: forcing outruns correction, failure onset.',
    source: 'M044',
    realityContact:
      'Model construct with structural parallels in control theory (gain margin). The cross-domain application is a structural correspondence, not an established empirical law.',
    distinctions: ['Model construct ≠ proved mathematical theorem', 'Structural correspondence ≠ universal empirical law'],
    dependencies: ['stability-inequality', 'istar'],
    lineage: { firstAppearance: 'M044', refinedBy: ['Glossary v3'], note: '' },
    companion: ['M044', 'D002'],
  },
  {
    id: 'gate-of-admissibility',
    symbol: 'Φ(x; I*) ≤ 0',
    name: 'Gate of Admissibility (Apex Operator)',
    register: 'Cross-Register · Constitutional Architecture',
    jurisdiction: 'Constitutional admissibility · All registers',
    evidenceStatus: 'Methodological Principle',
    canonicalStatus: 'Canonical',
    definition:
      'The unified cross-register admissibility operator. A system remains constitutionally coherent only when its movement remains admissible relative to its invariant reference I*. Φ(x; I*) ≤ 0: admissible. Φ(x; I*) > 0: inadmissible. This operator governs all registers; Φ_bio(x) is its biological-register instantiation.',
    source: 'C012',
    realityContact:
      'Methodological principle — the apex governing operator of the constitutional architecture.',
    distinctions: [
      'Φ(x; I*) ≠ Φ_bio(x) — cross-register admissibility operator ≠ biological completion functional',
      'Constitutional methodology ≠ empirical finding',
    ],
    dependencies: ['istar', 'xstar'],
    lineage: {
      firstAppearance: 'C012',
      refinedBy: ['Glossary v3 — distinguished from Φ_bio(x)'],
      note: 'Earlier corpus used Φ(x) for both. Glossary v3 register-locks Φ(x; I*) as the cross-register admissibility operator.',
    },
    companion: ['C012', 'D003', 'Plate XIV'],
  },
  {
    id: 'happiness',
    symbol: 'H',
    name: 'Standing State of Happiness (Expression Output)',
    register: 'Identity · Cross-Register',
    jurisdiction: 'Identity governance · Expression output',
    evidenceStatus: 'Model Construct',
    canonicalStatus: 'Canonical',
    definition:
      'Residual output of a system satisfying the admissibility gate. H := stable output under Φ(x; I*) ≤ 0. Binary: Φ ≤ 0 ⇒ H stable; Φ > 0 ⇒ H unavailable. H is not in the action space.',
    source: 'C013',
    realityContact:
      'Model construct. The observation that happiness as a direct pursuit undermines itself has parallels in psychological literature.',
    distinctions: [
      'Standing State definition of happiness ≠ psychological construct of well-being',
      'Binary model ≠ empirical description of affective states',
    ],
    dependencies: ['istar', 'gate-of-admissibility'],
    lineage: { firstAppearance: 'C013', refinedBy: ['Glossary v3'], note: '' },
    companion: ['C013', 'M045'],
  },
  {
    id: 'capacity',
    symbol: 'Γ',
    name: 'Verified Propagation Capacity',
    register: 'Cross-Register · Constitutional Architecture',
    jurisdiction: 'Constitutional execution · Post-gate capacity',
    evidenceStatus: 'Model Construct',
    canonicalStatus: 'Canonical',
    definition:
      'The system\'s verified ability to propagate an admissible state without loss, contradiction, or unauthorized effect. Γ is post-gate: it has no operational meaning unless Φ(x; I*) ≤ 0 is already satisfied.',
    source: 'P016',
    realityContact: 'Model construct — constitutional architecture element.',
    distinctions: [
      'Γ (Verified Propagation Capacity) ≠ Γ (Constitutional Convergence Operator in C-series formalism) — different uses of the same symbol; register-lock required when both are in scope',
      'Post-gate capacity ≠ raw throughput',
    ],
    dependencies: ['gate-of-admissibility', 'istar'],
    lineage: { firstAppearance: 'P016', refinedBy: ['Glossary v3 — symbol overload noted'], note: '' },
    companion: ['P016', 'Plate XVI'],
  },
  {
    id: 'execution',
    symbol: 'S',
    name: 'Authorized Execution Strength',
    register: 'Cross-Register · Constitutional Architecture',
    jurisdiction: 'Constitutional execution',
    evidenceStatus: 'Model Construct',
    canonicalStatus: 'Canonical',
    definition:
      'The resolved execution scalar: S = Φ · Γ². S emerges only when coherence satisfies admissibility and propagation capacity is verified.',
    source: 'P016',
    realityContact: 'Model construct — constitutional architecture element.',
    distinctions: ['S ≠ capability — S is authorized execution; capability is potential without admissibility'],
    dependencies: ['gate-of-admissibility', 'capacity'],
    lineage: { firstAppearance: 'P016', refinedBy: ['Glossary v3'], note: '' },
    companion: ['P016'],
  },
  {
    id: 'energy',
    symbol: 'E_k + E_p',
    name: 'Energy Term (Unified Functional)',
    register: 'Cross-Register · Physics analogy',
    jurisdiction: 'Unified system functional · Physical-register component',
    evidenceStatus: 'Structural Correspondence',
    canonicalStatus: 'Canonical',
    definition:
      'Kinetic and potential energy contribution to the unified system functional 𝓛(x,t). Structural correspondence with physics energy terms; used analogically in the corpus functional.',
    source: 'P019',
    realityContact: 'Structural correspondence with physics. Not claimed as literal energy measurements.',
    distinctions: ['Physics analogy ≠ empirical energy measurement'],
    dependencies: ['gate-of-admissibility'],
    lineage: { firstAppearance: 'P019', refinedBy: ['Glossary v3'], note: '' },
    companion: ['P019', 'Plate XIX'],
  },
  {
    id: 'execution-gate',
    symbol: 'Φ(x; I*) ≤ 0',
    name: 'Execution Gate',
    register: 'Cross-Register · Constitutional Architecture',
    jurisdiction: 'Pre-execution governance · Constitutional admissibility',
    evidenceStatus: 'Methodological Principle',
    canonicalStatus: 'Canonical',
    definition:
      'The pre-execution boundary that evaluates whether a proposed state x is admissible under I*. Does not generate, modify, or optimize outcomes — only permits or denies execution.',
    source: 'Cross-Plate',
    realityContact: 'Methodological principle — constitutional governance rule.',
    distinctions: ['Governance rule ≠ empirical finding'],
    dependencies: ['istar', 'gate-of-admissibility'],
    lineage: { firstAppearance: 'Cross-Plate', refinedBy: ['Glossary v3'], note: '' },
    companion: ['Plate X', 'Plate XVIII', 'D003'],
  },
  {
    id: 'audit-scalar',
    symbol: '𝓛',
    name: 'Audit Scalar',
    register: 'Cross-Register · Constitutional Architecture',
    jurisdiction: 'Constitutional audit · System convergence measure',
    evidenceStatus: 'Model Construct',
    canonicalStatus: 'Canonical',
    definition:
      'Unified scalar: 𝓛(x,t) = Φ(x) · Δ^p + E_k + E_p. State measure, not an authorization. 𝓛 → 0 indicates alignment with I*.',
    source: 'Cross-Plate',
    realityContact: 'Model construct — unified convergence measure for the constitutional architecture.',
    distinctions: ['State measure ≠ authorization (execution gate governs authorization separately)'],
    dependencies: ['gate-of-admissibility', 'admissibility-delta', 'energy'],
    lineage: { firstAppearance: 'Cross-Plate', refinedBy: ['Glossary v3'], note: '' },
    companion: ['Plate XIX', 'Plate XX'],
  },
  {
    id: 'witness',
    symbol: 'W',
    name: 'Witness Invariant',
    register: 'Identity · Cross-Register',
    jurisdiction: 'Identity governance · Observational continuity',
    evidenceStatus: 'Model Construct',
    canonicalStatus: 'Canonical',
    definition:
      'The invariant witnessing position through which changing states become observable without altering identity itself. dW/dt = 0 while x(t) varies.',
    source: 'P021',
    realityContact:
      'Model construct with parallels in contemplative traditions and phenomenological philosophy. Verification as a distinct psychological mechanism requires cognitive science reality contact.',
    distinctions: [
      'Model construct ≠ established neuroscientific structure',
      'W ≠ I* — witness is an observational position; I* is the identity coordinate',
    ],
    dependencies: ['istar'],
    lineage: { firstAppearance: 'P021', refinedBy: ['Glossary v3'], note: '' },
    companion: ['P021', 'Plate XXI'],
  },
  {
    id: 'ask-state',
    symbol: 'ASK / STATE',
    name: 'ASK and STATE',
    register: 'Constitutional Methodology',
    jurisdiction: 'Inquiry governance · Evidence architecture',
    evidenceStatus: 'Methodological Principle',
    canonicalStatus: 'Canonical',
    definition:
      'The constitutional distinction between inquiry and knowledge. ASK represents epistemic motion: it exists whenever a question remains unresolved. STATE represents retained reality: it exists only after reality contact has occurred. Secondary STATE ≠ primary STATE.',
    source: 'M081',
    realityContact: 'Methodological principle — the governing protocol for the trajectory inquiry architecture.',
    distinctions: [
      'ASK ≠ STATE',
      'Secondary STATE (synthesized evidence) ≠ primary STATE (independent practitioner evaluation)',
    ],
    dependencies: ['reality-contact'],
    lineage: { firstAppearance: 'M081', refinedBy: ['C018', 'C019', 'Glossary v3'], note: '' },
    companion: ['M081', 'C018', 'C019'],
  },
  {
    id: 'ask-1',
    symbol: 'ASK₁',
    name: 'ASK₁ — Identity Resolution',
    register: 'Constitutional Methodology',
    jurisdiction: 'Inquiry governance · Inquiry maturation',
    evidenceStatus: 'Methodological Principle',
    canonicalStatus: 'Canonical',
    definition:
      'The first phase of inquiry maturation. "What am I seeing?" Resolves whether a proposed variable is novel, already known, partially overlapping, or insufficiently evidenced. Identity precedes measurement.',
    source: 'M081',
    realityContact: 'Methodological principle for inquiry governance.',
    distinctions: ['ASK₁ must precede ASK₂'],
    dependencies: ['ask-state'],
    lineage: { firstAppearance: 'M081', refinedBy: ['Glossary v3'], note: '' },
    companion: ['M081'],
  },
  {
    id: 'ask-2',
    symbol: 'ASK₂',
    name: 'ASK₂ — Measurement Resolution',
    register: 'Constitutional Methodology',
    jurisdiction: 'Inquiry governance · Inquiry maturation',
    evidenceStatus: 'Methodological Principle',
    canonicalStatus: 'Canonical',
    definition:
      'The second phase of inquiry maturation, reachable only after ASK₁ resolves. "How is it measured?" Determines instrument, model, and admissible scenario conditions.',
    source: 'M081',
    realityContact: 'Methodological principle for inquiry governance.',
    distinctions: ['ASK₂ is unreachable without ASK₁ resolution'],
    dependencies: ['ask-1'],
    lineage: { firstAppearance: 'M081', refinedBy: ['Glossary v3'], note: '' },
    companion: ['M081'],
  },
  {
    id: 'constitutional-knowledge',
    symbol: 'Inquiry → Prediction → Reality → Knowledge',
    name: 'Constitutional Knowledge',
    register: 'Constitutional Methodology',
    jurisdiction: 'Inquiry governance · Knowledge formation',
    evidenceStatus: 'Methodological Principle',
    canonicalStatus: 'Canonical',
    definition:
      'A knowledge-formation sequence in which reality determines whether doctrine may exist. Reverses the common failure sequence. An inquiry may remain unresolved indefinitely without being promoted.',
    source: 'M081',
    realityContact: 'Methodological principle — the governing standard for corpus knowledge claims.',
    distinctions: ['Constitutional knowledge ≠ consensus', 'Unresolved inquiry ≠ failed inquiry'],
    dependencies: ['ask-state', 'reality-contact'],
    lineage: { firstAppearance: 'M081', refinedBy: ['C018', 'Glossary v3'], note: '' },
    companion: ['M081', 'C018'],
  },
  {
    id: 'module-existence-vs-inquiry-completion',
    symbol: 'Module ≠ Verdict',
    name: 'Module Existence vs. Inquiry Completion',
    register: 'Constitutional Methodology',
    jurisdiction: 'Inquiry governance · Audit discipline',
    evidenceStatus: 'Methodological Principle',
    canonicalStatus: 'Canonical',
    definition:
      'The distinction between "the auditor exists" and "the audit has completed." A module may exist and pass structurally while a specific inquiry has not yet been evaluated and therefore has no verdict.',
    source: 'M081',
    realityContact: 'Methodological principle — prevents premature closure.',
    distinctions: ['Module PASS ≠ inquiry verdict', 'Process existence ≠ process completion for any given case'],
    dependencies: ['ask-state', 'constitutional-knowledge'],
    lineage: { firstAppearance: 'M081', refinedBy: ['Glossary v3'], note: '' },
    companion: ['M081'],
  },
]
