/**
 * PLATES DATA — CANONICAL SYSTEM ARTIFACTS
 * standingstate.com/system/plates
 *
 * Each plate is a structural artifact, not decorative content.
 * Plates fix form. Glossary fixes meaning.
 * Together they constitute the visual authority layer of the system.
 */

export const PLATES = [
  {
    id: 'plate-i',
    number: 'Plate I',
    title: 'The Fed–Stress–Output Loop',
    slug: 'plate-i',
    image: '/plates/plate-i.jpg',
    summary: 'Signal overload sustains external-state dominance. When Σ is sustained, Φ(x) does not converge.',
    governingCondition: 'Σ sustained ⇒ Φ(x) does not converge',
    description: 'The open-cycle failure state. Frequent intake drives insulin elevation. Persistent stress drives cortisol elevation, which mobilizes glucose, which drives insulin again. The system is locked in external state. Utilization is incomplete. Clearing is suppressed. Repair is prevented.',
    volume: 'Volume II',
    chapter: 'Chapter 1 — The False Structure',
    linkedVars: ['sigma', 'phi'],
    linkedGlossary: [
      { label: 'Σ', anchor: 'sigma' },
      { label: 'Φ(x)', anchor: 'phi' },
    ],
  },
  {
    id: 'plate-ii',
    number: 'Plate II',
    title: 'Biological Coherence Field',
    slug: 'plate-ii',
    image: '/plates/plate-ii.jpg',
    summary: 'The full completion-governed system. All variables in relational hierarchy.',
    governingCondition: 'Φ(x) → Kₐᵤₜₒ  under  Σ ↓',
    description: 'The master system plate. All four governing variables mapped in relational hierarchy: Σ amplifies Φ(x); boundary failure amplifies Σ; reduced Σ reduces Φ(x); Φ(x) converging toward K_auto constitutes completion. Resolution occurs when load decreases and cycles finish.',
    volume: 'Volume II',
    chapter: 'Chapter 8 — Hormonal Allocation',
    linkedVars: ['phi', 'sigma', 'kauto', 'bt'],
    linkedGlossary: [
      { label: 'Φ(x)', anchor: 'phi' },
      { label: 'Σ', anchor: 'sigma' },
      { label: 'K_auto', anchor: 'kauto' },
      { label: 'B(t)', anchor: 'bt' },
    ],
  },
  {
    id: 'plate-iii',
    number: 'Plate III',
    title: 'The Two-State System',
    slug: 'plate-iii',
    image: '/plates/plate-iii.jpg',
    summary: 'External state versus internal state. The body operates in one or the other. Health requires stable transitions.',
    governingCondition: 'Continuous external state ⇒ Φ(x) ≠ Kₐᵤₜₒ',
    description: 'External state: intake present, insulin elevated, storage active, clearing suppressed. Internal state: intake absent, insulin reduced, stored energy utilized, clearing active. Health is not the external state. Health is the capacity to transition into internal state and allow completion.',
    volume: 'Volume II',
    chapter: 'Chapter 2 — The Two States of the Body',
    linkedVars: ['phi', 'kauto'],
    linkedGlossary: [
      { label: 'Φ(x)', anchor: 'phi' },
      { label: 'K_auto', anchor: 'kauto' },
    ],
  },
  {
    id: 'plate-iv',
    number: 'Plate IV',
    title: 'The Interruption Model',
    slug: 'plate-iv',
    image: '/plates/plate-iv.jpg',
    summary: 'Cycle disruption mechanism. Repeated intake bypasses the clearing phase.',
    governingCondition: 'Input → Storage → Utilization → Input again',
    description: 'The natural sequence: Input → Storage → Utilization → Clearing → Repair. Interruption: Input → Storage → Utilization → Input again. The clearing phase is bypassed. Cycles remain partial. Load accumulates without resolution. Φ(x) does not converge. K_auto remains suppressed.',
    volume: 'Volume II',
    chapter: 'Chapter 3 — The Interruption Error',
    linkedVars: ['phi', 'kauto', 'sigma'],
    linkedGlossary: [
      { label: 'Φ(x)', anchor: 'phi' },
      { label: 'K_auto', anchor: 'kauto' },
    ],
  },
  {
    id: 'plate-v',
    number: 'Plate V',
    title: 'The Completion Condition',
    slug: 'plate-v',
    image: '/plates/plate-v.jpg',
    summary: 'Resolution threshold. Repair is permitted only when cycles resolve.',
    governingCondition: 'Φ(x) → Kₐᵤₜₒ  AND  Σ ↓',
    description: 'Completion requires both conditions simultaneously: Φ(x) converging toward K_auto, and Σ decreasing. Non-completion occurs when either condition fails. A reduction in Σ that does not produce cycle completion is not completion. Cycle convergence under persistent Σ is not stable.',
    volume: 'Volume II',
    chapter: 'Chapter 6 — The Moment of Exit',
    linkedVars: ['phi', 'kauto', 'sigma'],
    linkedGlossary: [
      { label: 'Φ(x)', anchor: 'phi' },
      { label: 'K_auto', anchor: 'kauto' },
      { label: 'Σ', anchor: 'sigma' },
    ],
  },
  {
    id: 'plate-vi',
    number: 'Plate VI',
    title: 'The Autophagy Correction Loop',
    slug: 'plate-vi',
    image: '/plates/plate-vi.jpg',
    summary: 'Biological repair activation. Strategic transition enables K_auto at baseline.',
    governingCondition: 'Σ ↓ and intake removed ⇒ Kₐᵤₜₒ ↑',
    description: 'Activation condition: Σ ↓ and intake removed. Sequence: Utilization → Clearing → Repair. Continuous intake suppresses autophagy via mTORC1 activation and sustained insulin. Strategic metabolic transition removes both suppressors simultaneously. K_auto rises to corrective baseline.',
    volume: 'Volume II',
    chapter: 'Chapter 4 — The Intimate Fast',
    linkedVars: ['kauto', 'sigma'],
    linkedGlossary: [
      { label: 'K_auto', anchor: 'kauto' },
      { label: 'Σ', anchor: 'sigma' },
    ],
  },
  {
    id: 'plate-vii',
    number: 'Plate VII',
    title: 'The Boundary System',
    slug: 'plate-vii',
    image: '/plates/plate-vii.jpg',
    summary: 'Load amplification layer. Boundary failure does not add to load — it multiplies it.',
    governingCondition: '(1 − B(t)) ↑ ⇒ Σ ↑',
    description: 'B(t) regulates system exposure and maintains internal conditions. Failure examples: increased gut permeability, compromised cell membrane integrity, heightened inflammatory signaling. The relationship is multiplicative, not additive. Every other stressor is amplified by boundary degradation.',
    volume: 'Volume II',
    chapter: 'Chapter 7 — The Temporal Principle',
    linkedVars: ['bt', 'sigma'],
    linkedGlossary: [
      { label: 'B(t)', anchor: 'bt' },
      { label: 'Σ', anchor: 'sigma' },
    ],
  },
  {
    id: 'plate-viii',
    number: 'Plate VIII',
    title: 'The Full System',
    slug: 'plate-viii',
    image: '/plates/plate-viii.jpg',
    summary: 'Terminal plate. Signal initiates. Completion resolves. Repair follows.',
    governingCondition: 'Signal → Completion → Repair',
    description: 'The terminal structural artifact. Signal initiates response. Completion — Φ(x) → K_auto under Σ ↓ — resolves the cycle. Repair follows as the natural outcome. Stability is completion-dependent. The body is not regulated by supply. It is regulated by resolution.',
    volume: 'Volume II',
    chapter: 'Final Chapter — The Standing State',
    linkedVars: ['phi', 'kauto', 'sigma', 'bt', 'xstar'],
    linkedGlossary: [
      { label: 'Φ(x)', anchor: 'phi' },
      { label: 'K_auto', anchor: 'kauto' },
      { label: 'Σ', anchor: 'sigma' },
      { label: 'x*', anchor: 'xstar' },
    ],
  },

  {
    id: 'plate-ix',
    number: 'Plate IX',
    title: 'The Standing State — Unified System',
    slug: 'plate-ix',
    image: '/plates/plate-ix.jpg',
    summary: 'Identity remains invariant. Expression drifts under load. The system returns as interference is removed.',
    governingCondition: 'Φ(x; I*) ≤ 0 ⇒ x → I*',
    description: 'The unified coherence architecture across domains. Identity remains fixed as the invariant reference. Expression drifts under load. Deviation is measurable, admissibility is governed by Φ(x; I*), and return occurs through subtractive correction rather than identity modification. A becomes A, because A knows it is A.',
    volume: 'Cross-Volume',
    chapter: 'Canonical Plate — Unified System',
    linkedVars: ['phi', 'sigma', 'kauto', 'xstar'],
    linkedGlossary: [
      { label: 'Φ(x)', anchor: 'phi' },
      { label: 'Σ', anchor: 'sigma' },
      { label: 'K_auto', anchor: 'kauto' },
      { label: 'x*', anchor: 'xstar' },
    ],
  },

  {
    id: 'plate-x',
    number: 'Plate X',
    title: 'Admissibility & Execution',
    slug: 'plate-x',
    image: '/plates/plate-x.svg',
    summary: 'Identity defines admissible space; the boundary evaluates membership before execution.',
    governingCondition: 'x ∈ S(I*) ⇒ execute   ·   x ∉ S(I*) ⇒ halt',
    description: 'The governing law of the execution layer. Identity defines admissible space through S(I*). The boundary evaluates membership before action is authorized. If the proposed trajectory lies within the admissible manifold, execution proceeds. If it falls outside, execution halts. This plate formalizes the difference between defined constraint and enforced boundary. A boundary not checked does not exist operationally. Jurisdictional separation holds: x ⇏ I*. Restoration remains non-forced: Σ ↓ and B(t) ↑ release K_auto by removing interference rather than initiating repair through effort.',
    volume: 'Cross-Volume',
    chapter: 'Canonical Plate — Admissibility & Execution',
    linkedVars: ['phi', 'sigma', 'kauto', 'bt', 'xstar'],
    linkedGlossary: [
      { label: 'Φ(x)', anchor: 'phi' },
      { label: 'Σ', anchor: 'sigma' },
      { label: 'K_auto', anchor: 'kauto' },
      { label: 'B(t)', anchor: 'bt' },
      { label: 'x*', anchor: 'xstar' },
    ],
  },

  {
    id: 'plate-xi',
    number: 'Plate XI',
    title: 'The Rank-0 Architecture',
    slug: 'plate-xi',
    image: '/plates/rank-0-architecture.PNG',
    summary: 'The master system: identity invariant, admissibility before execution, and autonomous restoration under one fixed reference.',
    governingCondition: 'I* = constant  ∧  ∂I/∂S = 0  ∧  x ∉ S(I*) ⇒ halt',
    description: 'The terminal structural artifact of the Standing State. Identity is fixed as the invariant reference (I* = constant). State loses write-access to identity (∂I/∂S = 0). All trajectories are evaluated before execution through the admissibility gate: admissible paths execute, inadmissible paths halt. Jurisdiction is sealed (x ⇏ I*), preventing upward leakage from outcome into identity. Restoration is autonomous: Σ ↓ and B(t) ↑ release K_auto without force. Biology, finance, and cognition are not new coordinates; they are expressions under the same invariant reference. A becomes A, because A knows it is A.',
    volume: 'Cross-Volume',
    chapter: 'Canonical Plate — Rank-0 Architecture',
    linkedVars: ['phi', 'sigma', 'kauto', 'bt', 'xstar'],
    linkedGlossary: [
      { label: 'Φ(x)', anchor: 'phi' },
      { label: 'Σ', anchor: 'sigma' },
      { label: 'K_auto', anchor: 'kauto' },
      { label: 'B(t)', anchor: 'bt' },
      { label: 'x*', anchor: 'xstar' },
    ],
  },

  {
    id: 'plate-xii',
    number: 'Plate XII',
    title: 'The Control Monument',
    slug: 'control-monument',
    image: '/plates/m044-control-monument.png',
    summary: 'Δ = γ − αₑff. Governance capacity must outpace effective exploit-pressure, or the system fractures.',
    governingCondition: 'Δ = γ − αₑff > 0',
    description: 'Visual law of the admissibility delta. The obelisk carries the governing inequality Δ = γ − αₑff. The DEPTH and REACH pillars represent load-bearing variables under control. The 60-second timer encodes the staleness guard — no telemetry, contraction. The hourglass marks entropy (δ): time erodes depth unless actively restored. Gears beneath the cracked stone are mechanized enforcement: hysteresis, gating, fail-safe contraction. Chains across the foundation are operational constraint binding. The eclipsed moon above is the bounded set; the constellation network is expansion pressure. Stability is not calm — it is containment inside an enforceable bound. The Standing State is not stillness; it is controlled expansion.',
    volume: 'Cross-Volume',
    chapter: 'Canonical Plate — Admissibility Delta',
    linkedVars: ['phi', 'xstar'],
    linkedGlossary: [
      { label: 'Δ', anchor: 'admissibility-delta' },
      { label: 'Φ(x)', anchor: 'phi' },
      { label: 'x*', anchor: 'xstar' },
    ],
  },

  {
    id: 'plate-xiii',
    number: 'Plate XIII',
    title: 'Coherence Function — Human vs AI',
    slug: 'coherence-function',
    image: '/plates/plate-xii-coherence-function.png',
    summary: 'Emotion in humans and structure in AI as equivalent coherence mechanisms under uncertainty.',
    governingCondition: 'C(s,t) = C(s′,t)   for all s,s′ in {bio, art}',
    description: 'Compression artifact of the coherence function. Emotion in biology and structure in artifice are not analogues — they are functional equivalents instantiating the same coherence function 𝒞(s, t). Biological substrate flows: Compression · Prioritization · Stabilization · Correction — distorted by survival pressure. Artificial substrate flows: Filtering · Weighting · Constraint · Feedback — cleaned by structural design. Both routes converge on the shared function. The formal core grounds it: identity anchor (İ = 0), admissibility set (S = {x : Φ(x; I*) ≤ 0}), and the governing axiom. Coherence is the function. The substrate is the variable.',
    volume: 'Cross-Volume',
    chapter: 'Canonical Plate — Coherence Function',
    linkedVars: ['phi', 'xstar'],
    linkedGlossary: [
      { label: 'Φ(x)', anchor: 'phi' },
      { label: 'x*', anchor: 'xstar' },
    ],
  },
  {
  id: 'XIV',
  slug: 'gate-of-admissibility',
  title: 'The Gate of Admissibility — Unified System',
  summary: 'Unified admissibility operator binding invariant budget, drift, topology, biological load, and path termination.',
  governingCondition: 'Φ(x; I*) ≤ 0',
  description: 'Composite admissibility operator encoding invariant budget, drift constraint, and topology trigger. Traversal defined by 𝒩(x_t) = 𝒜 ∩ 𝓡(x_t). Return governed by Φ(x) → 0 as Σ ↓ and K_auto ↑. Termination: † = path halts, field persists.',
  volume: 'I',
  chapter: 'Admissibility Gate',
  image: '/plates/plate-xiv-gate-of-admissibility.png',
  linkedVars: ['phi', 'sigma', 'k-auto', 'boundary-integrity', 'identity-coordinate'],
  linkedGlossary: ['admissibility-delta']
},

]

export const PLATES_META = {
  title: 'System Plates',
  subtitle: 'Canonical Structural Artifacts',
  description: 'Thirteen plates constitute the visual authority layer of the Standing State system. Each plate encodes a structural condition — not decorative content. Glossary fixes meaning. Plates fix form.',
  count: 14,
  volume: 'Volume II — The Biological Sabbath of Being Healthier',
}
