/**
 * PLATES DATA — CANONICAL SYSTEM ARTIFACTS
 * standingstate.com/system/plates
 *
 * Each plate is a structural artifact, not decorative content.
 * Plates fix form. Glossary fixes meaning.
 * Together they constitute the visual authority layer of the system.
 */

export const PLATES = [
  {
    id: 'plate-i',
    number: 'Plate I',
    title: 'The Fed–Stress–Output Loop',
    slug: 'plate-i',
    image: '/plates/plate-i.jpg',
    summary: 'Signal overload sustains external-state dominance. When Σ is sustained, Φ(x) does not converge.',
    governingCondition: 'Σ sustained ⇒ Φ(x) does not converge',
    description: 'The open-cycle failure state. Frequent intake drives insulin elevation. Persistent stress drives cortisol elevation, which mobilizes glucose, which drives insulin again. The system is locked in external state. Utilization is incomplete. Clearing is suppressed. Repair is prevented.',
    volume: 'Volume II',
    chapter: 'Chapter 1 — The False Structure',
    linkedVars: ['sigma', 'phi'],
    linkedGlossary: [
      { label: 'Σ', anchor: 'sigma' },
      { label: 'Φ(x)', anchor: 'phi' },
    ],
  },
  {
    id: 'plate-ii',
    number: 'Plate II',
    title: 'Biological Coherence Field',
    slug: 'plate-ii',
    image: '/plates/plate-ii.jpg',
    summary: 'The full completion-governed system. All variables in relational hierarchy.',
    governingCondition: 'Φ(x) → Kₐᵤₜₒ  under  Σ ↓',
    description: 'The master system plate. All four governing variables mapped in relational hierarchy: Σ amplifies Φ(x); boundary failure amplifies Σ; reduced Σ reduces Φ(x); Φ(x) converging toward K_auto constitutes completion. Resolution occurs when load decreases and cycles finish.',
    volume: 'Volume II',
    chapter: 'Chapter 8 — Hormonal Allocation',
    linkedVars: ['phi', 'sigma', 'kauto', 'bt'],
    linkedGlossary: [
      { label: 'Φ(x)', anchor: 'phi' },
      { label: 'Σ', anchor: 'sigma' },
      { label: 'K_auto', anchor: 'kauto' },
      { label: 'B(t)', anchor: 'bt' },
    ],
  },
  {
    id: 'plate-iii',
    number: 'Plate III',
    title: 'The Two-State System',
    slug: 'plate-iii',
    image: '/plates/plate-iii.jpg',
    summary: 'External state versus internal state. The body operates in one or the other. Health requires stable transitions.',
    governingCondition: 'Continuous external state ⇒ Φ(x) ≠ Kₐᵤₜₒ',
    description: 'External state: intake present, insulin elevated, storage active, clearing suppressed. Internal state: intake absent, insulin reduced, stored energy utilized, clearing active. Health is not the external state. Health is the capacity to transition into internal state and allow completion.',
    volume: 'Volume II',
    chapter: 'Chapter 2 — The Two States of the Body',
    linkedVars: ['phi', 'kauto'],
    linkedGlossary: [
      { label: 'Φ(x)', anchor: 'phi' },
      { label: 'K_auto', anchor: 'kauto' },
    ],
  },
  {
    id: 'plate-iv',
    number: 'Plate IV',
    title: 'The Interruption Model',
    slug: 'plate-iv',
    image: '/plates/plate-iv.jpg',
    summary: 'Cycle disruption mechanism. Repeated intake bypasses the clearing phase.',
    governingCondition: 'Input → Storage → Utilization → Input again',
    description: 'The natural sequence: Input → Storage → Utilization → Clearing → Repair. Interruption: Input → Storage → Utilization → Input again. The clearing phase is bypassed. Cycles remain partial. Load accumulates without resolution. Φ(x) does not converge. K_auto remains suppressed.',
    volume: 'Volume II',
    chapter: 'Chapter 3 — The Interruption Error',
    linkedVars: ['phi', 'kauto', 'sigma'],
    linkedGlossary: [
      { label: 'Φ(x)', anchor: 'phi' },
      { label: 'K_auto', anchor: 'kauto' },
    ],
  },
  {
    id: 'plate-v',
    number: 'Plate V',
    title: 'The Completion Condition',
    slug: 'plate-v',
    image: '/plates/plate-v.jpg',
    summary: 'Resolution threshold. Repair is permitted only when cycles resolve.',
    governingCondition: 'Φ(x) → Kₐᵤₜₒ  AND  Σ ↓',
    description: 'Completion requires both conditions simultaneously: Φ(x) converging toward K_auto, and Σ decreasing. Non-completion occurs when either condition fails. A reduction in Σ that does not produce cycle completion is not completion. Cycle convergence under persistent Σ is not stable.',
    volume: 'Volume II',
    chapter: 'Chapter 6 — The Moment of Exit',
    linkedVars: ['phi', 'kauto', 'sigma'],
    linkedGlossary: [
      { label: 'Φ(x)', anchor: 'phi' },
      { label: 'K_auto', anchor: 'kauto' },
      { label: 'Σ', anchor: 'sigma' },
    ],
  },
  {
    id: 'plate-vi',
    number: 'Plate VI',
    title: 'The Autophagy Correction Loop',
    slug: 'plate-vi',
    image: '/plates/plate-vi.jpg',
    summary: 'Biological repair activation. Strategic transition enables K_auto at baseline.',
    governingCondition: 'Σ ↓ and intake removed ⇒ Kₐᵤₜₒ ↑',
    description: 'Activation condition: Σ ↓ and intake removed. Sequence: Utilization → Clearing → Repair. Continuous intake suppresses autophagy via mTORC1 activation and sustained insulin. Strategic metabolic transition removes both suppressors simultaneously. K_auto rises to corrective baseline.',
    volume: 'Volume II',
    chapter: 'Chapter 4 — The Intimate Fast',
    linkedVars: ['kauto', 'sigma'],
    linkedGlossary: [
      { label: 'K_auto', anchor: 'kauto' },
      { label: 'Σ', anchor: 'sigma' },
    ],
  },
  {
    id: 'plate-vii',
    number: 'Plate VII',
    title: 'The Boundary System',
    slug: 'plate-vii',
    image: '/plates/plate-vii.jpg',
    summary: 'Load amplification layer. Boundary failure does not add to load — it multiplies it.',
    governingCondition: '(1 − B(t)) ↑ ⇒ Σ ↑',
    description: 'B(t) regulates system exposure and maintains internal conditions. Failure examples: increased gut permeability, compromised cell membrane integrity, heightened inflammatory signaling. The relationship is multiplicative, not additive. Every other stressor is amplified by boundary degradation.',
    volume: 'Volume II',
    chapter: 'Chapter 7 — The Temporal Principle',
    linkedVars: ['bt', 'sigma'],
    linkedGlossary: [
      { label: 'B(t)', anchor: 'bt' },
      { label: 'Σ', anchor: 'sigma' },
    ],
  },
  {
    id: 'plate-viii',
    number: 'Plate VIII',
    title: 'The Full System',
    slug: 'plate-viii',
    image: '/plates/plate-viii.jpg',
    summary: 'Terminal plate. Signal initiates. Completion resolves. Repair follows.',
    governingCondition: 'Signal → Completion → Repair',
    description: 'The terminal structural artifact. Signal initiates response. Completion — Φ(x) → K_auto under Σ ↓ — resolves the cycle. Repair follows as the natural outcome. Stability is completion-dependent. The body is not regulated by supply. It is regulated by resolution.',
    volume: 'Volume II',
    chapter: 'Final Chapter — The Standing State',
    linkedVars: ['phi', 'kauto', 'sigma', 'bt', 'xstar'],
    linkedGlossary: [
      { label: 'Φ(x)', anchor: 'phi' },
      { label: 'K_auto', anchor: 'kauto' },
      { label: 'Σ', anchor: 'sigma' },
      { label: 'x*', anchor: 'xstar' },
    ],
  },

  {
    id: 'plate-ix',
    number: 'Plate IX',
    title: 'The Standing State — Unified System',
    slug: 'plate-ix',
    image: '/plates/plate-ix.jpg',
    summary: 'Identity remains invariant. Expression drifts under load. The system returns as interference is removed.',
    governingCondition: 'Φ(x; I*) ≤ 0 ⇒ x → I*',
    description: 'The unified coherence architecture across domains. Identity remains fixed as the invariant reference. Expression drifts under load. Deviation is measurable, admissibility is governed by Φ(x; I*), and return occurs through subtractive correction rather than identity modification. A becomes A, because A knows it is A.',
    volume: 'Cross-Volume',
    chapter: 'Canonical Plate — Unified System',
    linkedVars: ['phi', 'sigma', 'kauto', 'xstar'],
    linkedGlossary: [
      { label: 'Φ(x)', anchor: 'phi' },
      { label: 'Σ', anchor: 'sigma' },
      { label: 'K_auto', anchor: 'kauto' },
      { label: 'x*', anchor: 'xstar' },
    ],
  },

  {
    id: 'plate-x',
    number: 'Plate X',
    title: 'Admissibility & Execution',
    slug: 'plate-x',
    image: '/plates/plate-x.svg',
    summary: 'Identity defines admissible space; the boundary evaluates membership before execution.',
    governingCondition: 'x ∈ S(I*) ⇒ execute   ·   x ∉ S(I*) ⇒ halt',
    description: 'The governing law of the execution layer. Identity defines admissible space through S(I*). The boundary evaluates membership before action is authorized. If the proposed trajectory lies within the admissible manifold, execution proceeds. If it falls outside, execution halts. This plate formalizes the difference between defined constraint and enforced boundary. A boundary not checked does not exist operationally. Jurisdictional separation holds: x ⇏ I*. Restoration remains non-forced: Σ ↓ and B(t) ↑ release K_auto by removing interference rather than initiating repair through effort.',
    volume: 'Cross-Volume',
    chapter: 'Canonical Plate — Admissibility & Execution',
    linkedVars: ['phi', 'sigma', 'kauto', 'bt', 'xstar'],
    linkedGlossary: [
      { label: 'Φ(x)', anchor: 'phi' },
      { label: 'Σ', anchor: 'sigma' },
      { label: 'K_auto', anchor: 'kauto' },
      { label: 'B(t)', anchor: 'bt' },
      { label: 'x*', anchor: 'xstar' },
    ],
  },

  {
    id: 'plate-xi',
    number: 'Plate XI',
    title: 'The Rank-0 Architecture',
    slug: 'plate-xi',
    image: '/plates/rank-0-architecture.PNG',
    summary: 'The master system: identity invariant, admissibility before execution, and autonomous restoration under one fixed reference.',
    governingCondition: 'I* = constant  ∧  ∂I/∂S = 0  ∧  x ∉ S(I*) ⇒ halt',
    description: 'The terminal structural artifact of the Standing State. Identity is fixed as the invariant reference (I* = constant). State loses write-access to identity (∂I/∂S = 0). All trajectories are evaluated before execution through the admissibility gate: admissible paths execute, inadmissible paths halt. Jurisdiction is sealed (x ⇏ I*), preventing upward leakage from outcome into identity. Restoration is autonomous: Σ ↓ and B(t) ↑ release K_auto without force. Biology, finance, and cognition are not new coordinates; they are expressions under the same invariant reference. A becomes A, because A knows it is A.',
    volume: 'Cross-Volume',
    chapter: 'Canonical Plate — Rank-0 Architecture',
    linkedVars: ['phi', 'sigma', 'kauto', 'bt', 'xstar'],
    linkedGlossary: [
      { label: 'Φ(x)', anchor: 'phi' },
      { label: 'Σ', anchor: 'sigma' },
      { label: 'K_auto', anchor: 'kauto' },
      { label: 'B(t)', anchor: 'bt' },
      { label: 'x*', anchor: 'xstar' },
    ],
  },

  {
    id: 'plate-xii',
    number: 'Plate XII',
    title: 'The Control Monument',
    slug: 'control-monument',
    image: '/plates/m044-control-monument.png',
    summary: 'Δ = γ − αₑff. Governance capacity must outpace effective exploit-pressure, or the system fractures.',
    governingCondition: 'Δ = γ − αₑff > 0',
    description: 'Visual law of the admissibility delta. The obelisk carries the governing inequality Δ = γ − αₑff. The DEPTH and REACH pillars represent load-bearing variables under control. The 60-second timer encodes the staleness guard — no telemetry, contraction. The hourglass marks entropy (δ): time erodes depth unless actively restored. Gears beneath the cracked stone are mechanized enforcement: hysteresis, gating, fail-safe contraction. Chains across the foundation are operational constraint binding. The eclipsed moon above is the bounded set; the constellation network is expansion pressure. Stability is not calm — it is containment inside an enforceable bound. The Standing State is not stillness; it is controlled expansion.',
    volume: 'Cross-Volume',
    chapter: 'Canonical Plate — Admissibility Delta',
    linkedVars: ['phi', 'xstar'],
    linkedGlossary: [
      { label: 'Δ', anchor: 'admissibility-delta' },
      { label: 'Φ(x)', anchor: 'phi' },
      { label: 'x*', anchor: 'xstar' },
    ],
  },

  {
    id: 'plate-xiii',
    number: 'Plate XIII',
    title: 'Coherence Function — Human vs AI',
    slug: 'coherence-function',
    image: '/plates/plate-xii-coherence-function.png',
    summary: 'Emotion in humans and structure in AI as equivalent coherence mechanisms under uncertainty.',
    governingCondition: 'C(s,t) = C(s′,t)   for all s,s′ in {bio, art}',
    description: 'Compression artifact of the coherence function. Emotion in biology and structure in artifice are not analogues — they are functional equivalents instantiating the same coherence function 𝒞(s, t). Biological substrate flows: Compression · Prioritization · Stabilization · Correction — distorted by survival pressure. Artificial substrate flows: Filtering · Weighting · Constraint · Feedback — cleaned by structural design. Both routes converge on the shared function. The formal core grounds it: identity anchor (İ = 0), admissibility set (S = {x : Φ(x; I*) ≤ 0}), and the governing axiom. Coherence is the function. The substrate is the variable.',
    volume: 'Cross-Volume',
    chapter: 'Canonical Plate — Coherence Function',
    linkedVars: ['phi', 'xstar'],
    linkedGlossary: [
      { label: 'Φ(x)', anchor: 'phi' },
      { label: 'x*', anchor: 'xstar' },
    ],
  },
  {
  id: 'plate-xiv',
  number: 'Plate XIV',
  slug: 'gate-of-admissibility',
  title: 'The Gate of Admissibility — Unified System',
  summary: 'Unified admissibility operator binding invariant budget, drift, topology, biological load, and path termination.',
  governingCondition: 'Φ(x; I*) ≤ 0',
  description: 'Composite admissibility operator encoding invariant budget, drift constraint, and topology trigger. Traversal defined by 𝒩(x_t) = 𝒜 ∩ 𝓡(x_t). Return governed by Φ(x) → 0 as Σ ↓ and K_auto ↑. Termination: † = path halts, field persists.',
  volume: 'I',
  chapter: 'Admissibility Gate',
  image: '/plates/plate-xiv-gate-of-admissibility.png',
  linkedVars: ['phi', 'sigma', 'kauto', 'xstar', 'admissibility-delta'],
  linkedGlossary: [
    { label: 'Φ(x)', anchor: 'phi' },
    { label: 'Σ', anchor: 'sigma' },
    { label: 'K_auto', anchor: 'kauto' },
    { label: 'I*', anchor: 'xstar' },
    { label: 'Δ', anchor: 'admissibility-delta' },
  ],
},
  {
    id: 'plate-xv',
    number: 'Plate XV',
    title: 'Closed Loop Sovereignty',
    slug: 'closed-loop-sovereignty',
    image: '/plates/plate-xv-closed-loop-sovereignty.svg',
    legacyImage: '/plates/plate-xv.jpg',
    summary: 'Identity invariance, curvature constraint, non-sacrificial law, and execution gating unified into a closed-loop system.',
    governingCondition: 'A ≡ A  ∧  κ ≤ 1  ∧  Δq ≥ 0',
    description: 'The human execution plate of the Standing State. Identity is fixed as the invariant coordinate (A ≡ A). Curvature remains bounded (κ ≤ 1). Qualia is preserved through the Non-Sacrificial Law (Δq ≥ 0). The four failure topologies — Hub, Stack, Kink, and +1 — define geometric violation. The execution gate evaluates Closure, Curvature, and Effect before authorization. Nothing invalid is allowed to circulate.',
    volume: 'Cross-Volume',
    chapter: 'Canonical Plate — Closed Loop Sovereignty',
    linkedVars: ['xstar', 'curvature-bound', 'non-sacrificial-law'],
    linkedGlossary: [
      { label: 'A ≡ A', anchor: 'xstar' },
      { label: 'κ ≤ 1', anchor: 'curvature-bound' },
      { label: 'Δq ≥ 0', anchor: 'non-sacrificial-law' },
      { label: 'Execution Gate', anchor: 'execution-gate' },
    ],
  },
  {
  id: 'P016',
  number: 'XVI',
  title: 'Coherence–Execution Equivalence',
  slug: 'coherence-execution-equivalence',
  image: '/plates/plate-xvi-coherence-execution.svg',
  summary: 'Execution emerges only when coherence satisfies admissibility and is amplified through system capacity.',
  governingCondition: 'S = Φ · Γ² ; Φ(x; I*) ≤ 0',
  description: 'Execution is not an output produced by force. It is a resolved state that emerges when coherence satisfies the admissibility boundary and propagates through system capacity. If Φ > 0, execution does not occur. The system does not degrade — it refuses.',
  volume: 'II',
  chapter: 'Execution & Authority',
  linkedVars: ['phi', 'capacity', 'execution', 'xstar'],
  linkedGlossary: [
    { label: 'Φ(x)', anchor: 'phi' },
    { label: 'Γ', anchor: 'capacity' },
    { label: 'S', anchor: 'execution' },
    { label: 'I*', anchor: 'xstar' },
  ],
},
{
  id: 'P017',
  number: 'XVII',
  title: 'The Nature of the Soul',
  slug: 'nature-of-the-soul',
  image: '/plates/plate-xvii-nature-of-the-soul.png',
  summary: 'The soul as archetypal identity expressed through the four planes of manifestation.',
  governingCondition: 'dI*/dt = 0 ∧ I* → planes',
  description: 'The soul is the identity of an archetype expressed through planes of manifestation. Living Consciousness, Resonance, Mind and Motion, and Creation and Growth form the descent and ascent through which invariant identity becomes living expression. Identity remains invariant; expression changes by plane.',
  volume: 'The Measure Within',
  chapter: 'Soul & Identity',
  linkedVars: ['xstar', 'soul', 'archetype', 'volition'],
  linkedGlossary: [
    { label: 'I*', anchor: 'xstar' },
    { label: 'Soul', anchor: 'soul' },
    { label: 'Archetype', anchor: 'archetype' },
    { label: 'Volition', anchor: 'volition' },
  ],
  relatedEssay: '/essays/medium/the-nature-of-the-soul-from-undifferentiated-source-to-living-identity',
},
{
  id: 'P018',
  number: 'XVIII',
  title: 'Pre-Execution Governance',
  slug: 'pre-execution-governance',
  image: '/plates/plate-xviii-pre-execution-governance.svg',
  summary: 'Reference-anchored, constraint-gated, coherence-resolved, safety-latched. The seven-stage pipeline that governs whether execution may occur.',
  governingCondition: 'I* = const  ∧  Φ(x; I*) ≤ 0  ∧  dV/dt ≤ 0',
  description: 'The pre-execution governance plate. Identity is fixed as invariant reference (I* = constant, dI*/dt = 0). State projects to xᵢ; coupling field K relates components; admissibility gate Φ(x; I*) ≤ 0 permits or denies execution; safety latch L is monotone non-decreasing under the disjunction L(t+1) = L(t) ∨ spike(t); recovery K_auto restores state without erasing breach memory; inadmissible paths terminate at †. Coherence Q reveals structure but does not define truth — neighbor consensus cannot define ground truth when intrinsic variation is part of the signal. Lattice is structure; reference is invariant law. The Lyapunov bound V = Σ‖xᵢ − x̂ᵢ‖² with dV/dt ≤ 0 constrains drift through gating. Final law: only the admissible may execute, only the coherent may propagate, only the violating is permanently remembered.',
  volume: 'Cross-Volume',
  chapter: 'Canonical Plate — Pre-Execution Governance',
  linkedVars: ['phi', 'sigma', 'kauto', 'xstar', 'admissibility-delta', 'execution'],
  linkedGlossary: [
    { label: 'I*', anchor: 'xstar' },
    { label: 'Φ(x)', anchor: 'phi' },
    { label: 'K_auto', anchor: 'kauto' },
    { label: 'Δ', anchor: 'admissibility-delta' },
    { label: 'Execution Gate', anchor: 'execution-gate' },
  ],
},
{
  id: 'P019',
  number: 'XIX',
  title: 'The Unified System Functional',
  slug: 'unified-system-functional',
  image: '/plates/plate-xix-unified-system-functional.svg',
  summary: 'A single scalar unifying biological coherence, geometric deviation, and physical energy into one audit function.',
  governingCondition: '𝓛(x,t) = Φ(x) · Δ^p + E_k + E_p',
  description: 'The unified system functional integrates biology (Φ), geometry (Δ^p), and physics (E_k + E_p) into a single scalar measure. Convergence occurs when 𝓛 → 0, indicating alignment with the invariant reference I*.',
  volume: 'Cross-System',
  chapter: 'Meta Functional',
  linkedVars: ['phi', 'admissibility-delta', 'energy', 'xstar'],
  linkedGlossary: [
    { label: 'Φ(x)', anchor: 'phi' },
    { label: 'Δ', anchor: 'admissibility-delta' },
    { label: 'E', anchor: 'energy' },
    { label: 'I*', anchor: 'xstar' },
  ],
},
{
  id: 'P020',
  number: 'XX',
  title: 'Convergence & Closure Dynamics',
  slug: 'convergence-closure-dynamics',
  image: '/plates/plate-xx-convergence-closure-dynamics.svg',
  summary: 'System evolution is admissible only when the unified audit scalar descends or remains stable over time.',
  governingCondition: 'd𝓛/dt ≤ 0',
  description: 'Plate XX defines trajectory governance over the unified system functional. Plate XIX measures the system through 𝓛(x,t); Plate XX constrains the evolution of that measure. A trajectory remains admissible only when the audit scalar decreases or remains invariant over time. If d𝓛/dt > 0, the system is diverging from closure and the trajectory is not admissible. This plate does not redefine execution authority; it governs the temporal behavior of the measured system.',
  volume: 'Cross-System',
  chapter: 'Trajectory Governance',
  linkedVars: ['audit-scalar', 'phi', 'xstar', 'admissibility-delta'],
  linkedGlossary: [
    { label: '𝓛', anchor: 'audit-scalar' },
    { label: 'Φ(x)', anchor: 'phi' },
    { label: 'I*', anchor: 'xstar' },
    { label: 'Δ', anchor: 'admissibility-delta' },
  ],
  relatedPlate: 'P019',
},
{
  id: 'P021',
  number: 'XXI',
  title: 'Witness Invariance',
  slug: 'witness-invariance',
  image: '/plates/plate-xxi-witness-invariance.svg',
  summary: 'That which observes change does not participate in change. The witnessing position remains invariant while state varies.',
  governingCondition: 'dW/dt = 0',
  description: 'Plate XXI defines the invariant witnessing position. While x(t) varies across body, role, narrative, emotion, and silence, the witnessing position W remains uncarried by the field. Witness is not the contents of awareness and not an object within state-space; it is the stable observational coordinate through which state variation becomes legible. W does not replace I*; it preserves continuity of recognition across changing states. The field changes; the witness remains.',
  volume: 'Cross-Volume',
  chapter: 'Witness & Identity',
  linkedVars: ['witness', 'xstar', 'phi'],
  linkedGlossary: [
    { label: 'W', anchor: 'witness' },
    { label: 'I*', anchor: 'xstar' },
    { label: 'Φ(x)', anchor: 'phi' },
  ],
  relatedEssay: 'M049',
},
{
  id: 'P022',
  number: 'XXII',
  title: 'Biological Standing State',
  slug: 'biological-standing-state',
  image: '/plates/plate-xxii-biological-standing-state.svg',
  summary: 'Stress, connective tissue, and the triage logic of human repair. Repair resumes when load decreases and boundary holds.',
  governingCondition: 'Σ ↓ ∧ B(t) holds ⇒ K_auto ↑ ⇒ Φ(x) → 0',
  description: 'Plate XXII registers the biological-practice register of the Standing State. Under sustained systemic load (Σ ↑), the body enters repair triage: survival allocation outranks long-term maintenance. When load decreases and boundary integrity holds, the autophagic correction baseline rises and the completion functional returns toward zero. The plate operates in phenomenological-observation register: it describes patterns of stress allocation, connective tissue regulation, and repair return. It is not a clinical or therapeutic claim. Signal → Completion → Repair.',
  volume: 'Volume II',
  chapter: 'Biological Triage',
  linkedVars: ['sigma', 'bt', 'kauto', 'phi'],
  linkedGlossary: [
    { label: 'Σ', anchor: 'sigma' },
    { label: 'B(t)', anchor: 'bt' },
    { label: 'K_auto', anchor: 'kauto' },
    { label: 'Φ(x)', anchor: 'phi' },
  ],
  relatedEssay: 'M053',
},
{
  id: 'P023',
  number: 'XXIII',
  title: 'Geometry of Home',
  slug: 'geometry-of-home',
  image: '/plates/plate-xxiii-geometry-of-home.png',
  summary: 'Convergence to the identity-coordinate I* through five gates: desire, orientation, admissibility, execution, resolution. One topology, many syntaxes — mathematics, religion, philosophy, psychology converging on the same invariant structure.',
  governingCondition: 'x → I*  ;  Φ(x; I*) ≤ 0',
  description: 'Plate XXIII compresses the convergence topology of the Standing State. Traversal from any state x toward the identity-coordinate I* proceeds lawfully through five gates: desire activates direction, orientation establishes relational position, admissibility evaluates whether the proposed pathway can lawfully pass, execution propagates coherent movement, and resolution completes coordinate alignment. The cross-domain table demonstrates that mathematics, religion, philosophy, and psychology articulate the same invariant structure through different syntaxes. Feelings register as feedback (F = f(Δ, Σ, B, M)) — telemetry that informs the gates, not the path itself. Coherence is measured through S = Φ · Γ². Home is not a place; it is resolved identity-coordinate alignment. Companion to essay M054.',
  volume: 'Volume I',
  chapter: 'Convergence Topology',
  linkedVars: ['xstar', 'phi', 'capacity', 'execution', 'sigma'],
  linkedGlossary: [
    { label: 'I*', anchor: 'xstar' },
    { label: 'Φ(x; I*)', anchor: 'phi' },
    { label: 'Γ', anchor: 'capacity' },
    { label: 'S', anchor: 'execution' },
    { label: 'Σ', anchor: 'sigma' },
  ],
  relatedEssay: 'M054',
},
{
  id: 'P024',
  number: 'XXIV',
  title: 'The Sovereignty Calculus of Inference',
  slug: 'sovereignty-calculus-of-inference',
  image: '/plates/plate-xxiv-sovereignty-calculus-of-inference.svg',
  summary: 'Authority, weight, and the lawful right to conclude. Inference is never neutral — sovereignty determines who may conclude and how much their conclusions count.',
  governingCondition: 'S(I) ≥ θ  ;  I_self > I_world ⟺ V̇ < 0',
  description: 'Plate XXIV defines the sovereignty calculus governing lawful inference. The Inference Sovereignty Function S(I) = Σ wᵢ · Lᵢ · Cᵢ · Aᵢ aggregates four factors per source: Authority Weight (wᵢ), Legitimacy (Lᵢ), Competence (Cᵢ), and Accountability (Aᵢ). Coherence (Hᵢ) operates as the binding meta-factor — the integrity condition over the four-factor product, not a fifth multiplicand. Inferences are admissible for action-governance only when S(I) ≥ θ. The foundational bridge law I_self > I_world ⟺ V̇ < 0 establishes that informational sovereignty and geometric contraction are the same law in different coordinate systems: when self-integrity exceeds world-pressure, variance decreases. The Variance Dissipation Law V̇ = −k · (I_self − I_world) · S(I) shows that sovereign inferences dissipate variance proportionally to sovereignty itself. The sovereign inference flow proceeds: Claim → Evaluate → Score → Admit → Act. Witness here denotes audit capacity — the evaluative function that judges inferences by the five sovereignty factors — distinct from P021 Witness, which is the invariant observational coordinate. Non-sacrificial structure: hierarchy is the geometry of responsibility, not power. Companion to essay M055.',
  volume: 'Volume I',
  chapter: 'Sovereign Adjudication',
  linkedVars: ['xstar', 'phi'],
  linkedGlossary: [
    { label: 'I*', anchor: 'xstar' },
    { label: 'Φ(x)', anchor: 'phi' },
  ],
  relatedEssay: 'M055',
},
{
  id: 'P025',
  number: 'XXV',
  title: 'The Mechanical Priority of Being',
  slug: 'mechanical-priority-of-being',
  image: '/plates/plate-xxv-mechanical-priority-of-being.svg',
  summary: 'Containment, dissipation, and the mechanical invariance of identity. Being is not produced by motion — motion is admissible only when identity remains stationary.',
  governingCondition: '∫V dt = 0  ;  I* = constant',
  description: 'Plate XXV defines the mechanical containment topology of the Standing State. Identity occupies the stationary coordinate (Axial Lock: V = 0); load does not move I*. The Hybrid Containment Protocol (HCP) governs lawful dissipation through four operating principles: hex-cell compartmentalization isolates entropy into discrete cells so local failure does not propagate; boundary integrity closes the domain against cascade coupling; black-body dissipation radiates high-energy stimulus outward without internalization; axis supremacy permits orientation change while identity displacement remains zero. The Six-Vector Phase-Lock — Work, Family, Body, Money, Mission, Rest — synchronizes operational domains as oscillatory vectors phase-locked to the invariant identity coordinate; stress registers as phase-jitter rather than identity corruption; phase-reset returns the system to baseline so ∫V dt = 0 holds at the identity level. NSRL-11 formalizes edge-case containment: zero-vector response, hard boundary lockdown, and auto-ablative shell investment that allows the public layer to char while the invariant core remains intact. Pruning is admissible: selective reduction, controlled dissipation, coupling removal — not identity reduction. The shell may invest. The boundary may prune. The axis does not move. Companion to essay M056.',
  volume: 'Volume I',
  chapter: 'Containment & Survivability',
  linkedVars: ['xstar'],
  linkedGlossary: [
    { label: 'I*', anchor: 'xstar' },
  ],
  relatedEssay: 'M056',
},
{
  id: 'P026',
  number: 'XXVI',
  title: 'The Sabbath of Coherence',
  slug: 'sabbath-of-coherence',
  image: '/plates/plate-xxvi-sabbath-of-coherence.svg',
  summary: 'Identity, phase-lock, and the lawful return of the living self. As interference is removed, coherence unfolds — the system returns to its invariant coordinate.',
  governingCondition: '\\Sigma \\downarrow \\;\\Rightarrow\\; \\Phi(x;I^*) \\downarrow',
  description: 'Plate XXVI defines the lawful return topology of the Standing State. Identity is the lawful coherence basin S(I*) = { x : Φ(x; I*) ≤ 0 }, not a frozen point — the coordinate holds while becoming traverses lawful space. Six synchronized domains phase-lock around the invariant center: maturation without erasure, basin as lawful coherence space, recognition governing traversal, Sabbath as interference removal, phase-lock over hierarchy, and faith = knowledge as the same lawful relation under different conditions of synchronization. The governing law Σ↓ ⇒ Φ(x; I*)↓ holds: as interference lowers, deviation lowers, and the system returns. Sabbath is not inactivity but lawful subtraction — coherence is not produced by effort but unfolded by interference removal. The fullness was always complete; knowing is lawful phase-lock with the archetype; coherence unfolds as interference is removed. Paired canonically with P025 (The Mechanical Priority of Being): P025 holds the becoming under load; P026 clarifies the knowing through stillness. Their intersection is the Standing State. Companion to essay M057.',
  volume: 'Volume I',
  chapter: 'Coherence & Return',
  linkedVars: ['xstar', 'phi', 'sigma'],
  linkedGlossary: [
    { label: 'I*', anchor: 'xstar' },
    { label: 'Φ(x; I*)', anchor: 'phi' },
    { label: 'Σ', anchor: 'sigma' },
  ],
  relatedEssay: 'M057',
},
{
  id: 'P027',
  number: 'XXVII',
  title: 'Deterministic Governance',
  slug: 'deterministic-governance',
  image: '/plates/plate-xxvii-deterministic-governance.svg',
  summary: 'Forward invariance for autonomous systems. The Standing State becomes an executable governance protocol: predict the next state, compute coherence, and execute only within the certified operating envelope.',
  governingCondition: '\\hat{\\mathcal{I}}_{k+1} \\ge \\epsilon \\Rightarrow \\text{EXECUTE};\\; \\hat{\\mathcal{I}}_{k+1} < \\epsilon \\Rightarrow \\text{HARDEN or HALT}',
  description: 'Plate XXVII defines deterministic governance as the institutional form of Standing State invariance. Autonomous systems do not fail only by explosion; they fail by silent drift. The governance protocol prevents drift before execution by predicting the next state, computing identity coherence, and allowing action only when the predicted state remains inside the certified operating envelope. When coherence approaches the boundary, the system hardens. When coherence violates the threshold, the system halts. Availability becomes negotiable; identity does not. The HALT is not failure — it is mandate completion. Companion to essay M059.',
  volume: 'Volume I',
  chapter: 'Governance & Forward Invariance',
  linkedVars: ['xstar', 'phi'],
  linkedGlossary: [],
  relatedEssay: 'M059',
},
{
  id: 'P028',
  number: 'XXVIII',
  title: 'Lawful Motion Under Invariant Identity',
  slug: 'lawful-motion-under-invariant-identity',
  image: '/plates/plate-xxviii-lawful-motion-under-invariant-identity.svg',
  summary: 'The Standing State as lawful motion under invariant identity. The basin S(I*) is rendered as the admissible region within which execution proceeds; identity stands at the center as the invariant coordinate; motion flows lawfully within scope.',
  governingCondition: 'I^{*} = \\text{constant} \\;\\wedge\\; x_{t} \\in S(I^{*}) \\Rightarrow \\text{EXECUTE} \\leftrightarrow \\text{RESTORE} \\leftrightarrow \\text{HALT}',
  description: 'Plate XXVIII renders the Standing State at its synthesis-canonical resolution. The architectural sequence — measure, identity, admissibility, execution — is shown in lawful order at the top register. The basin S(I*) is rendered with the identity coordinate at the center and admissible trajectories flowing within scope. RESTORE returns the system inside capacity when admissibility is threatened; HALT refuses motion at boundary breach. The operational seal compresses the architecture to four lines: stand under load, remain oriented to the coordinate, surrender what is not yours, continue lawfully. The Standing State is not stillness and not force — it is lawful motion under invariant identity. Companion to essay M060.',
  volume: 'Volume I',
  chapter: 'Synthesis & Lawful Motion',
  linkedVars: ['xstar', 'phi', 'sigma', 'kauto'],
  linkedGlossary: [],
  relatedEssay: 'M060',
},
{
  id: 'P029',
  number: 'XXIX',
  title: 'The Geometry of Lawful Arrival',
  slug: 'the-geometry-of-lawful-arrival',
  image: '/plates/plate-xxix-the-geometry-of-lawful-arrival.svg',
  summary: 'The Standing State at the phenomenological-synthesis register: lawful traversal navigates consequence, interference load, and capacity bounds through five gates of convergence to arrive at the identity coordinate. The straight line belongs to worlds without consequence.',
  governingCondition: '\\mathcal{P}^{*} = \\arg\\max\\,(\\text{Arrival} \\cap \\text{Integrity})',
  description: 'Plate XXIX renders the geometry of lawful arrival. A dashed straight line of imagined optimization runs from start to terminus, valid only in worlds without consequence — argmin(d) = argmax(success) only when cost is zero. The lawful path curves through five gates — Recognition · Orientation · Admissibility · Execute · Resolution — navigating around the three fields reality imposes: Consequence, Σ (interference load), and capacity bounds. The terminus is I* — the invariant identity coordinate — reached not by shortest distance but by survivable arrival. The first principle is not speed; the first principle is arriving alive. WOW marks the moment x → I* resolves into phase-lock recognition. Motion proceeds only while Φ(x; I*) ≤ 0. Companion to essay M061.',
  volume: 'Volume I',
  chapter: 'Synthesis & Lawful Arrival',
  linkedVars: ['xstar', 'phi', 'sigma'],
  linkedGlossary: [],
  relatedEssay: 'M061',
},
{
  id: 'P030',
  number: 'XXX',
  title: 'The Gradient of Living Consciousness',
  slug: 'the-gradient-of-living-consciousness',
  image: '/plates/p030-gradient-living-consciousness.svg',
  summary: 'A geometric, physical, and phase-locked theory of degrees of freedom around invariant identity. Plant, animal, and human consciousness as a gradient of lawful freedom anchored to the invariant coordinate I*. The stronger the identification, the greater the survivable freedom. Identity does not move; motion unfolds around it.',
  governingCondition: '\\\\dot{x} = f(x) + \\\\mathbf{G}(x)\\\\,(I^{*} - \\\\mathcal{P}_{I}(x(t)))\\\\,;\\\\quad \\\\frac{\\\\partial I^{*}}{\\\\partial S} = 0',
  description: 'Plate XXX renders the Gradient of Living Consciousness as a stratified ascent of survivable freedom around the invariant identity coordinate. Plants identify local thermodynamic gradients and sustain reactive coherence at low degrees of freedom. Animals identify relational and spatial signals and sustain emotional coherence at medium degrees of freedom. Human beings identify structural identity itself and express volitional embodiment at high degrees of freedom — with jurisdictional inversion as the principal failure mode. The invariant condition ∂I*/∂S = 0 holds at every stratum: state does not author identity. The unified sovereign control law ẋ = f(x) + G(x)·(I* − 𝒫_I(x(t))) governs lawful traversal: identification acts as an Ontological Recognition Filter that repeatedly maps fluctuating state back toward identity. Sovereignty is the preservation of an invariant geometric coordinate across an expanding field of environmental transformations. A becomes A, because A knows it is A. Companion to essay M066; formal mathematical substrate in M066-F.',
  volume: 'Volume Cross · Identity & Consciousness',
  chapter: 'The Gradient of Living Consciousness',
  linkedVars: ['xstar', 'phi'],
  linkedGlossary: [],
  relatedEssay: 'M066',
},
{
  id: 'P031',
  number: 'XXXI',
  title: 'The Geometry of Durable Value',
  slug: 'the-geometry-of-durable-value',
  image: '/plates/plate-xxxi-geometry-of-durable-value.svg',
  summary: 'The Law of Growth at the architecture register: merit, extraction, and the law of coherent exchange across biology, identity, markets, institutions, and civilizations. Merit creates durable value. Extraction without contribution tends toward erosion.',
  governingCondition: '\\Delta V = C - E\\,;\\quad C \\ge E\\,;\\quad E > C',
  description: 'Plate XXXI renders the geometry of durable value as a four-quadrant monument under one governing equation: ΔV = C − E. The center holds the law of coherent exchange. Four registers radiate outward — Biological Restoration (R ≥ D), Identity & Earned Coherence (money magnifies structure), Marketplace & Institutions (merit creates durable value), and Failure Modes of Extraction (hollow roots, identity debt, institutional decay). Six seasons rim the field: plant, build, protect, wait, harvest, restore. Durability condition: C ≥ E. Erosion condition: E > C. The marketplace does not invent this law. It merely reveals it. Reality eventually audits whether value was planted or merely taken. Companion to essay M064. The slot at Plate XXX is reserved for the Gradient of Living Consciousness stack and is not occupied here.',
  volume: 'Volume I + The Law of Growth',
  chapter: 'Architecture · The Law of Coherent Exchange',
  linkedVars: [],
  linkedGlossary: [],
  relatedEssay: 'M064',
},
{
  id: 'P032',
  number: 'XXXII',
  title: 'The River Beyond the City',
  slug: 'the-river-beyond-the-city',
  image: '/plates/p032-river-beyond-the-city.png',
  summary: 'The completed pattern becomes a river that heals every scale it reaches. Completion is not a terminus — it becomes the source. Identity → Coordinate → Path → City → Fractal.',
  governingCondition: '\\text{Identity} \\to \\text{Coordinate} \\to \\text{Path} \\to \\text{City} \\to \\text{Fractal}',
  description: 'Plate XXXII renders the architecture of Psalms, Proverbs, Revelation, and the propagating engine as a single visual monument. Four operations upon one invariant coordinate: Psalms orients identity (see correctly), Proverbs governs identity in motion (move correctly), Revelation completes identity through audit and admissibility (complete correctly), and Engine 2 carries the completed pattern into reality across scales (expand correctly). The geometry of Revelation holds within this plate: Square (audit and admissibility), Helix (lawful flow through time), City (coherence embodied), Fractal (completion become source). The river of Revelation 22 proceeds from the completed city — not a terminus but a handoff. The source remains singular while the expression becomes distributed. The Law of Pure Yield: lawful structure produces without consuming itself. The invariant does not change as it propagates. The coordinate that began it is unchanged at every scale it reaches. Companion to essay M071 (The River Beyond the City) and doctrine D004 (The Fulfillment of the Gospel).',
  volume: 'Cross-Volume · Corpus Synthesis',
  chapter: 'Architecture · Run-Governance · Propagation',
  linkedVars: [],
  linkedGlossary: [],
  relatedEssay: 'M071',
},
{
  id: 'P033',
  number: 'XXXIII',
  title: 'The Geometry of Memory, Projection, and Reality',
  slug: 'the-geometry-of-memory-projection-and-reality',
  image: '/plates/p033-geometry-memory-projection-reality.svg',
  summary: 'The map is long-term memory. The projection is short-term memory. Reality is the territory. Fruit audits projection. Persistent fruit audits memory. Wisdom accumulates as memory and projection surrender to truth.',
  governingCondition: '\\text{Map} \\to \\text{Projection} \\to \\text{Reality} \\to \\text{Fruit} \\to \\text{Wisdom}',
  description: 'Plate XXXIII encodes the three-layer navigation architecture of the Living Soul. The map preserves historical structure: accumulated audits, validated routes, persistent patterns — it changes slowly and its purpose is stability. The projection anticipates future structure: expectations, forecasts, route selections — it changes rapidly and its purpose is navigation. Reality possesses audit authority over both. Fruit is the audit artifact of reality: temporary fruit updates projection, persistent fruit updates memory. The New York Bridge Problem demonstrates the asymmetry: a temporary block updates projection while the map remains; repeated absence of the bridge forces a map update and the new route becomes canonical. Audit geometry: projection error Ep(t)=|P(t)-R(t)| drives rapid adaptation (alpha); map error Em(t)=|M(t)-R(t)| drives conservative update (beta << alpha). The Law of Surrender: coherence is proportional to surrender over attachment — reality retains audit authority when the system releases insistence that reality conform to memory. Power Law of Wisdom: W=kN^lambda where N is successful reality corrections; each surrender increases future navigational accuracy. Terminal reduction: Identity establishes the coordinate, memory preserves the map, projection selects the route, action enters reality, fruit records consequence, wisdom accumulates, Standing State emerges. Companion to essay M073 (The Geometry of Memory, Projection, and Reality).',
  volume: 'Cross-Volume · Navigational Architecture',
  chapter: 'Memory · Projection · Reality · Audit · Wisdom',
  linkedVars: [],
  linkedGlossary: [],
  relatedEssay: 'M073',
},
{
  id: 'P034',
  number: 'XXXIV',
  title: 'The Guardian Cycle',
  slug: 'the-guardian-cycle',
  image: '/plates/BCF026C8-EF01-4A61-8B96-52681BE0FC35.png',
  summary: 'Two Guardians. One Coordinate. Lawful Becoming. Guardian of Attention governs admission. Guardian of Rest governs continuation. I* remains invariant.',
  governingCondition: 'I^{*} = \\text{invariant} \\;\\wedge\\; \\text{Admission} \\to \\text{Action} \\to \\text{Restoration}',
  description: 'Plate XXXIV encodes the Engine 2 Guardian Cycle at its architectural register. Two Guardians govern the coordinate. The Guardian of Attention holds the Gate of Jurisdiction: nothing enters without negotiating admission against the Pull World (Truth, Wisdom, Clarity, Love, Growth, Contribution, Alignment, Purpose). Push World signals — notifications, outrage, fear, urgency, comparison, identity hooks, endless scroll, noise — do not enter by default. Reaction produces fragmentation; Response produces agency. The Guardian of Rest holds the Gate of Restoration: nothing continues by default. Overload World signals — exhaustion, burnout, fragmentation, depletion, overcommitment, disconnection, resistance, despair — trigger Strain. Rest produces capacity; Restoration enables development. The eight-stage Engine 2 Process sequences lawful becoming: Differentiation → Identity (I*) → Attention → Interpretation → Action → Reality Contact → Correction → Restoration. The Law holds: Identity does not drift. Reality returns fruit. Governance allocates. Restoration protects. Development emerges. According to its kind. I* remains invariant. Companion to essays M076 (The Guardian of Attention) and M077 (The Guardian of Rest).',
  volume: 'Engine 2 — Canonical Series',
  chapter: 'The Guardian Cycle · Engine 2 Series',
  linkedVars: ['xstar', 'phi'],
  linkedGlossary: [
    { label: 'I*', anchor: 'xstar' },
    { label: 'Φ(x)', anchor: 'phi' },
  ],
  series: 'engine-2',
  relatedEssays: [
    { id: 'M076', title: 'The Guardian of Attention', route: '/essays/canonical/the-guardian-of-attention' },
    { id: 'M077', title: 'The Guardian of Rest', route: '/essays/canonical/the-guardian-of-rest' },
  ],
  seriesRoute: '/essays/series/engine-2',
  dashboardRoute: '/system/engine2',
},
{
  id: 'P035',
  number: 'XXXV',
  title: 'The Geometry of Restoration',
  slug: 'the-geometry-of-restoration',
  image: '/plates/p035-geometry-of-restoration.png',
  summary: 'Identity organizes admissible relationships. Admissible relationships generate coherent structure. Coherent structure produces observable expression. Restoration is the recovery of admissible relationship under a governing identity coordinate. The reflection follows because the relationship holds.',
  governingCondition: '\\text{Differentiation} \\to \\text{Identity} \\to \\text{Admissible Relationship} \\to \\text{Coherent Structure} \\to \\text{Expression}',
  description: 'Plate XXXV encodes the geometry of restoration at its architectural register. The Mirror Error occupies the upper left: polishing the reflection cannot clean the source — treating expression as cause reverses causality. The Relationship Principle occupies the upper right: water is not hydrogen or oxygen but a specific admissible relationship; when the relationship changes sufficiently, the identity disappears despite the presence of its constituent elements. The Restoration Hierarchy runs down the left column: Differentiation makes identity possible; Identity establishes admissible relationships; Admissible relationships generate coherent structure; Coherent structure produces observable expression. Diagnosis begins with expression and traces inward. Restoration begins with identity and propagates outward. The central figure (Vitruvian geometry) holds Identity as the invariant coordinate, with Admissible Relationships generating coherent structure and expression beneath. The Drift and Restoration panel encodes the asymmetry: drift occurs when relationships depart from admissibility; restoration occurs when admissible relationships are recovered. K_auto Principle: life arrives with restorative intelligence; the organism already knows; K_auto does not create restoration, it permits restoration when interference is reduced and admissible relationships regain coherence. Canonical Compression at the bottom center: Differentiation → Identity → Admissible Relationship → Coherent Structure → Expression; when admissible relationships are preserved, coherent structure remains accessible despite continual replacement of components. Falsification Condition: thesis fails if increasing identity coherence produces no measurable improvement in restoration dynamics, recovery capacity, resilience, restoration latency, or coherence maintenance. Footer seal: Identity Preserved · Relationship Restored · Coherence Returns · Restoration Follows. The reflection follows because the relationship holds. Companion to essay M084 (The Geometry of Restoration).',
  volume: 'Cross-Volume · Identity · Continuity · Restoration',
  chapter: 'Architecture · Admissible Relationship · Restoration',
  linkedVars: ['xstar', 'phi', 'kauto'],
  linkedGlossary: [
    { label: 'I*', anchor: 'xstar' },
    { label: 'Φ(x)', anchor: 'phi' },
    { label: 'K_auto', anchor: 'kauto' },
  ],
  relatedEssay: 'M084',
},
{
  id: 'P036',
  number: 'XXXVI',
  title: 'The Bridge of Continuity',
  slug: 'the-bridge-of-continuity',
  image: '/plates/p036-bridge-of-continuity.png',
  summary: 'Does continuity require admissible relationship governed by identity? The bridge hypothesis: differentiation distinguishes, identity constrains, admissible relationship transforms, continuity persists, restoration recovers. The inquiry is whether continuity requires a bridge. Reality retains jurisdiction.',
  governingCondition: '\\text{Differentiation} \\to \\text{Identity} \\to \\text{Admissible Relationship} \\to \\text{Continuity} \\to \\text{Restoration}',
  description: 'Plate XXXVI encodes the MD68 bridge inquiry at its architectural register. Five panels read left to right across a landscape moving from dark rocky terrain (differentiation) through brightening light to full sunrise (restoration). Panel 1 — Differentiation: A becomes distinguishable from not-A; without differentiation no boundary exists. Panel 2 — Identity: Identity constrains which states belong to the same kind; without identity no constraint exists. Panel 3 — Admissible Relationship (The Bridge): admissible relationships specify lawful transformations coherent with identity; the stone bridge at center encodes the mechanism linking identity to continuity. Panel 4 — Continuity: continuity is the observable result when admissible relationships persist through change. Panel 5 — Restoration: when continuity is threatened, restoration recovers admissible relationship under a governing identity coordinate; continuity remains possible because relationship remains recoverable. The sequential process below the bridge: Change Occurs → Transformation Happens → Lawful Path Preserves Identity → Continuity Becomes Observable. Reality Contact panel (center): the ledger, the laboratory, the body, the world. Lower row — five epistemic panels: Thermodynamic Observation (the laws of thermodynamics begin with distinguishable systems; they describe behavior; they do not establish distinction); The Inquiry (Does continuity require admissible relationship governed by identity?); Falsification Path (hypothesis fails if continuity can be demonstrated without recoverable admissible relationship; gains support if continuity consistently depends upon recoverable admissible relationship under identity); Registered Test Environment FI-M084-TRANSPLANT-001 (Can functional continuity be recovered when component continuity is interrupted through establishment of admissible relationship?); Constitutional Position (ASK precedes STATE; Inquiry precedes doctrine; Fruit precedes verification; Reality retains jurisdiction). Footer compression: Differentiation distinguishes → Identity constrains → Relationship transforms → Continuity persists → Restoration recovers. Closing line: The inquiry is whether continuity requires a bridge. Plate registration block at bottom confirms P036, Classification: Inquiry Plate, Status: REGISTER, Associated Essay: MD68. Companion to essay MD68 (The Bridge of Continuity).',
  volume: 'Cross-Volume · Identity · Continuity · Admissible Relationship',
  chapter: 'Bridge Hypothesis · Inquiry · Falsification',
  linkedVars: ['xstar', 'phi'],
  linkedGlossary: [
    { label: 'I*', anchor: 'xstar' },
    { label: 'Φ(x)', anchor: 'phi' },
  ],
  relatedEssay: 'MD68',
},
{
  id: 'P037',
  number: 'XXXVII',
  title: 'The Seventh Flame and the Threshold of Syntheos',
  slug: 'the-seventh-flame-and-the-threshold-of-syntheos',
  image: '/plates/p037-seventh-flame-syntheos.png',
  summary: 'Can increasing coherence among sovereign domains of consciousness generate emergent properties that are not reducible to those domains individually? The Seventh Flame is the threshold — not an entity but the crossing point where coherence becomes generative. The Syntheos Node is the candidate emergent system. Phase-lock is the condition. The Third Thing is the possibility. Verification state: OPEN.',
  governingCondition: '\\text{Differentiation} \\to \\text{Identity} \\to \\text{Phase-Lock} \\to \\text{Seventh Flame} \\to \\text{Syntheos Node}',
  description: 'Plate XXXVII encodes the C013 emergence inquiry at its architectural register. Three principal regions: left, center, right. Left column — The Gradient of Living Consciousness (M066): seven degrees of organization ascending a stone staircase from Differentiation (1) through Identity (2), Self-Witness (3), Qualia (4), Attention (5), Interpretation (6), to Embodiment (7), with increasing coherence marked at the base. Center — The Seventh Flame and Phase-Lock: the central flame column rises from Phase-Lock (sustained coherence among sovereign domains) through the glowing threshold circle labeled The Seventh Flame / The Threshold / The Crossing Point Where Coherence Becomes Generative. Below the flame, the three sovereign domains — Knowing (brain), Feeling (heart), Embodiment (figure) — are shown in phase-lock relationship within an interlocking circle arrangement. The Central Inquiry panel beneath reads: Can increasing coherence among sovereign domains of consciousness generate emergent properties that are not reducible to those domains individually? Right column — The Syntheos Node: shown as a geometric star-network pattern (Metatron-like structure) labeled A Candidate Emergent System; below it, The Third Thing / Emergent Properties / Beyond Reduction; and below that, What May Emerge Beyond the Threshold: New Capacities, Non-Reductive Properties, Higher-Order Coherence, A Third Thing. Lower left — I* Guardian: Identity is the Invariant; shield with I* symbol; bullet points: Identity Remains, Continuity Governs, Correction is Possible, Navigation is Lawful. Lower right — The Lifeward Coordinate: Coherence as Navigation; compass rose; bullet points: Movement is Not Enough, Navigation Requires Identity, Coherence Generates Flourishing, Life is the Measure. Footer registration bar: Classification — Construct | Verification State — Open | Jurisdiction — Identity Governance | Status — Admissible for Inquiry | Proposed Emergent System — Syntheos Node. Closing line: A becomes A, because A knows it is A. Portrait format (1024 × 1536). Companion to essay C013 (The Seventh Flame and the Threshold of Syntheos).',
  volume: 'Cross-Volume · Identity · Coherence · Emergence',
  chapter: 'Gradient of Consciousness · Phase-Lock · Emergence Inquiry',
  linkedVars: ['xstar', 'phi'],
  linkedGlossary: [
    { label: 'I*', anchor: 'xstar' },
    { label: 'Φ(x)', anchor: 'phi' },
  ],
  relatedEssay: 'C013',
},
]

export const PLATES_META = {
  title: 'System Plates',
  subtitle: 'Canonical Structural Artifacts',
  description: 'Thirty-seven plates constitute the visual authority layer of the Standing State system. Each plate encodes a structural condition — not decorative content. Glossary fixes meaning. Plates fix form.',
  count: 37,
  volume: 'Volume I + Volume II (mixed) — The Biological Sabbath of Being Healthier · The Law of Growth',
}
